ifcs:
  options:
    log_level: "info"
nodes:
- node_id: "0"
  options:
    sku: "configs/sku/innovium.77700_B"
    netdev:
    - auto_create: "no"
      multi_interface: "yes"
    buffer_management_mode: "bootstrap_lossless"
    max_lossless_tc: "2"
    txring:
    - txring_id: "0"
      desc_count: "1024"
      prio: "1"
      netdev: "true"
    - txring_id: "1"
      desc_count: "1024"
      prio: "1"
      netdev: "true"
    - txring_id: "2"
      desc_count: "1024"
      prio: "1"
      netdev: "true"
    - txring_id: "3"
      desc_count: "1024"
      prio: "1"
      netdev: "true"
    rxring:
    - rxring_id: "0"
      desc_count: "1024"
      prio: "1"
      netdev: "true"
      queues: "0, 4, 8, 12, 16, 20, 24, 28, 32, 36, 40, 44"
    - rxring_id: "1"
      desc_count: "1024"
      prio: "1"
      netdev: "true"
      queues: "1, 5, 9, 13, 17, 21, 25, 29, 33, 37, 41, 45"
    - rxring_id: "2"
      desc_count: "1024"
      prio: "1"
      netdev: "true"
      queues: "2, 6, 10, 14, 18, 22, 26, 30, 34, 38, 42, 46"
    - rxring_id: "3"
      desc_count: "1024"
      prio: "1"
      netdev: "true"
      queues: "3, 7, 11, 15, 19, 23, 27, 31, 35, 39, 43, 47"
    sys_clk: "1720"
    ifc_clk: "1200"
    mac_clk: "1340"

  devports:
  - id: "0"
    sysport: "65"
    type: "cpu"
  - fec: "KRFEC"
    id: "1"
    lanes: "0:4"
    serdes_group: "31"
    speed: "100G"
    sysport: "1"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "2"
    lanes: "4:4"
    serdes_group: "31"
    speed: "100G"
    sysport: "2"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "3"
    lanes: "4:4"
    serdes_group: "30"
    speed: "100G"
    sysport: "3"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "4"
    lanes: "0:4"
    serdes_group: "30"
    speed: "100G"
    sysport: "4"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "5"
    lanes: "0:4"
    serdes_group: "29"
    speed: "100G"
    sysport: "5"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "6"
    lanes: "4:4"
    serdes_group: "29"
    speed: "100G"
    sysport: "6"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "7"
    lanes: "4:4"
    serdes_group: "28"
    speed: "100G"
    sysport: "7"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "8"
    lanes: "0:4"
    serdes_group: "28"
    speed: "100G"
    sysport: "8"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "9"
    lanes: "0:4"
    serdes_group: "27"
    speed: "100G"
    sysport: "9"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "10"
    lanes: "4:4"
    serdes_group: "27"
    speed: "100G"
    sysport: "10"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "11"
    lanes: "4:4"
    serdes_group: "26"
    speed: "100G"
    sysport: "11"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "12"
    lanes: "0:4"
    serdes_group: "26"
    speed: "100G"
    sysport: "12"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "13"
    lanes: "0:4"
    serdes_group: "25"
    speed: "100G"
    sysport: "13"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "14"
    lanes: "4:4"
    serdes_group: "25"
    speed: "100G"
    sysport: "14"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "15"
    lanes: "4:4"
    serdes_group: "24"
    speed: "100G"
    sysport: "15"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "16"
    lanes: "0:4"
    serdes_group: "24"
    speed: "100G"
    sysport: "16"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "17"
    lanes: "0:4"
    serdes_group: "23"
    speed: "100G"
    sysport: "17"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "18"
    lanes: "4:4"
    serdes_group: "23"
    speed: "100G"
    sysport: "18"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "19"
    lanes: "4:4"
    serdes_group: "22"
    speed: "100G"
    sysport: "19"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "20"
    lanes: "0:4"
    serdes_group: "22"
    speed: "100G"
    sysport: "20"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "21"
    lanes: "0:4"
    serdes_group: "21"
    speed: "100G"
    sysport: "21"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "22"
    lanes: "4:4"
    serdes_group: "21"
    speed: "100G"
    sysport: "22"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "23"
    lanes: "4:4"
    serdes_group: "20"
    speed: "100G"
    sysport: "23"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "24"
    lanes: "0:4"
    serdes_group: "20"
    speed: "100G"
    sysport: "24"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "25"
    lanes: "0:4"
    serdes_group: "19"
    speed: "100G"
    sysport: "25"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "26"
    lanes: "4:4"
    serdes_group: "19"
    speed: "100G"
    sysport: "26"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "27"
    lanes: "4:4"
    serdes_group: "18"
    speed: "100G"
    sysport: "27"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "28"
    lanes: "0:4"
    serdes_group: "18"
    speed: "100G"
    sysport: "28"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "29"
    lanes: "0:4"
    serdes_group: "17"
    speed: "100G"
    sysport: "29"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "30"
    lanes: "4:4"
    serdes_group: "17"
    speed: "100G"
    sysport: "30"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "31"
    lanes: "4:4"
    serdes_group: "16"
    speed: "100G"
    sysport: "31"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "32"
    lanes: "0:4"
    serdes_group: "16"
    speed: "100G"
    sysport: "32"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "33"
    lanes: "0:4"
    serdes_group: "15"
    speed: "100G"
    sysport: "33"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "34"
    lanes: "4:4"
    serdes_group: "15"
    speed: "100G"
    sysport: "34"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "35"
    lanes: "4:4"
    serdes_group: "14"
    speed: "100G"
    sysport: "35"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "36"
    lanes: "0:4"
    serdes_group: "14"
    speed: "100G"
    sysport: "36"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "37"
    lanes: "0:4"
    serdes_group: "13"
    speed: "100G"
    sysport: "37"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "38"
    lanes: "4:4"
    serdes_group: "13"
    speed: "100G"
    sysport: "38"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "39"
    lanes: "4:4"
    serdes_group: "12"
    speed: "100G"
    sysport: "39"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "40"
    lanes: "0:4"
    serdes_group: "12"
    speed: "100G"
    sysport: "40"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "41"
    lanes: "0:4"
    serdes_group: "11"
    speed: "100G"
    sysport: "41"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "42"
    lanes: "4:4"
    serdes_group: "11"
    speed: "100G"
    sysport: "42"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "43"
    lanes: "4:4"
    serdes_group: "10"
    speed: "100G"
    sysport: "43"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "44"
    lanes: "0:4"
    serdes_group: "10"
    speed: "100G"
    sysport: "44"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "45"
    lanes: "0:4"
    serdes_group: "9"
    speed: "100G"
    sysport: "45"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "46"
    lanes: "4:4"
    serdes_group: "9"
    speed: "100G"
    sysport: "46"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "47"
    lanes: "4:4"
    serdes_group: "8"
    speed: "100G"
    sysport: "47"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "48"
    lanes: "0:4"
    serdes_group: "8"
    speed: "100G"
    sysport: "48"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "49"
    lanes: "0:4"
    serdes_group: "7"
    speed: "100G"
    sysport: "49"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "50"
    lanes: "4:4"
    serdes_group: "7"
    speed: "100G"
    sysport: "50"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "51"
    lanes: "4:4"
    serdes_group: "6"
    speed: "100G"
    sysport: "51"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "52"
    lanes: "0:4"
    serdes_group: "6"
    speed: "100G"
    sysport: "52"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "53"
    lanes: "0:4"
    serdes_group: "5"
    speed: "100G"
    sysport: "53"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "54"
    lanes: "4:4"
    serdes_group: "5"
    speed: "100G"
    sysport: "54"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "55"
    lanes: "4:4"
    serdes_group: "4"
    speed: "100G"
    sysport: "55"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "56"
    lanes: "0:4"
    serdes_group: "4"
    speed: "100G"
    sysport: "56"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "57"
    lanes: "0:4"
    serdes_group: "3"
    speed: "100G"
    sysport: "57"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "58"
    lanes: "4:4"
    serdes_group: "3"
    speed: "100G"
    sysport: "58"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "59"
    lanes: "4:4"
    serdes_group: "2"
    speed: "100G"
    sysport: "59"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "60"
    lanes: "0:4"
    serdes_group: "2"
    speed: "100G"
    sysport: "60"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "61"
    lanes: "0:4"
    serdes_group: "1"
    speed: "100G"
    sysport: "61"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "62"
    lanes: "4:4"
    serdes_group: "1"
    speed: "100G"
    sysport: "62"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "63"
    lanes: "4:4"
    serdes_group: "0"
    speed: "100G"
    sysport: "63"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "64"
    lanes: "0:4"
    serdes_group: "0"
    speed: "100G"
    sysport: "64"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  isg:
  - id: "0"
    lane_swap: "01234567"
    rx_polarity: "01110001"
    tx_polarity: "00101001"
  - id: "1"
    lane_swap: "01234567"
    rx_polarity: "11100100"
    tx_polarity: "10111111"
  - id: "2"
    lane_swap: "01234567"
    rx_polarity: "00010001"
    tx_polarity: "00100010"
  - id: "3"
    lane_swap: "01234567"
    rx_polarity: "11011101"
    tx_polarity: "00101010"
  - id: "4"
    lane_swap: "01234567"
    rx_polarity: "10010101"
    tx_polarity: "10111110"
  - id: "5"
    lane_swap: "01234567"
    rx_polarity: "10111001"
    tx_polarity: "01101000"
  - id: "6"
    lane_swap: "01234567"
    rx_polarity: "01110011"
    tx_polarity: "01110110"
  - id: "7"
    lane_swap: "01234567"
    rx_polarity: "10111001"
    tx_polarity: "01001000"
  - id: "8"
    lane_swap: "01234567"
    rx_polarity: "01000000"
    tx_polarity: "11000100"
  - id: "9"
    lane_swap: "01234567"
    rx_polarity: "10100100"
    tx_polarity: "10001010"
  - id: "10"
    lane_swap: "01234567"
    rx_polarity: "00011101"
    tx_polarity: "11000110"
  - id: "11"
    lane_swap: "01234567"
    rx_polarity: "00000101"
    tx_polarity: "01000111"
  - id: "12"
    lane_swap: "01234567"
    rx_polarity: "11100000"
    tx_polarity: "01111000"
  - id: "13"
    lane_swap: "01234567"
    rx_polarity: "00101111"
    tx_polarity: "10011111"
  - id: "14"
    lane_swap: "01234567"
    rx_polarity: "00011000"
    tx_polarity: "00101001"
  - id: "15"
    lane_swap: "01234567"
    rx_polarity: "00110110"
    tx_polarity: "10110111"
  - id: "16"
    lane_swap: "01234567"
    rx_polarity: "00000111"
    tx_polarity: "00101001"
  - id: "17"
    lane_swap: "01234567"
    rx_polarity: "10001000"
    tx_polarity: "10100111"
  - id: "18"
    lane_swap: "01234567"
    rx_polarity: "11111110"
    tx_polarity: "00011001"
  - id: "19"
    lane_swap: "01234567"
    rx_polarity: "10011010"
    tx_polarity: "10010101"
  - id: "20"
    lane_swap: "01234567"
    rx_polarity: "01100000"
    tx_polarity: "00101001"
  - id: "21"
    lane_swap: "01234567"
    rx_polarity: "01111001"
    tx_polarity: "10010111"
  - id: "22"
    lane_swap: "01234567"
    rx_polarity: "11010011"
    tx_polarity: "00101001"
  - id: "23"
    lane_swap: "01234567"
    rx_polarity: "01111011"
    tx_polarity: "10110111"
  - id: "24"
    lane_swap: "01234567"
    rx_polarity: "11101011"
    tx_polarity: "00101001"
  - id: "25"
    lane_swap: "01234567"
    rx_polarity: "11010111"
    tx_polarity: "10110111"
  - id: "26"
    lane_swap: "01234567"
    rx_polarity: "00101101"
    tx_polarity: "00100001"
  - id: "27"
    lane_swap: "01234567"
    rx_polarity: "11011001"
    tx_polarity: "11000111"
  - id: "28"
    lane_swap: "01234567"
    rx_polarity: "01010011"
    tx_polarity: "00100001"
  - id: "29"
    lane_swap: "01234567"
    rx_polarity: "01111001"
    tx_polarity: "10110111"
  - id: "30"
    lane_swap: "01234567"
    rx_polarity: "00110001"
    tx_polarity: "00101001"
  - id: "31"
    lane_swap: "01234567"
    rx_polarity: "01101101"
    tx_polarity: "10110101"
  - id: "32"
    lane_swap: "01234567"
    rx_polarity: "00000000"
    tx_polarity: "00000000"
