ifcs:
  options:
    log_level: "info"
nodes:
- node_id: "0"
  options:
    sd_low_power_mode_global_default: "true"
    sku: "configs/sku/innovium.77700_A"
    netdev:
    - auto_create: "no"
      multi_interface: "yes"
    pcie_attn: "10, 0, 0, 0"
    pcie_post: "10, 0, 0, 0"
    pcie_pre1: "0, 0, 0, 0"
    buffer_management_mode: "api_driven"
    wred_cr_ip_proto_list: "17"
    cr_assignment_mode: "1"
    max_lossless_tc: "2"
    ilpm_enable: "1"
    ecn_stats_enable: "1"
    forward_profile: "IFCS_FORWARD_PROFILE_ID_PROFILE_E"
    led_cfg_sck_rate: "0x5"
    led_refresh_precliff_timer: "0x18eec2"
    led_refresh_cliff_timer: "0x15e"
    led_cfg_pic_stream_mode: "1"
    led_refresh_tmr_ctl_enable: "1"
    txring:
    - txring_id: "0"
      desc_count: "1024"
      prio: "1"
      netdev: "true"
    - txring_id: "1"
      desc_count: "1024"
      prio: "1"
      netdev: "true"
    - txring_id: "2"
      desc_count: "1024"
      prio: "1"
      netdev: "true"
    - txring_id: "3"
      desc_count: "1024"
      prio: "1"
      netdev: "true"
    rxring:
    - rxring_id: "0"                                         
      desc_count: "1024"                                     
      prio: "1"     
      netdev: "true"      
      queues: "0, 3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39"  
    - rxring_id: "1"                                         
      desc_count: "1024"                                     
      prio: "1"    
      netdev: "true"      
      queues: "1, 4, 7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40"  
    - rxring_id: "2"                                         
      desc_count: "1024"                                     
      prio: "1"
      netdev: "true"      
      queues: "2, 5, 8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 47" 
    - rxring_id: "3"                                         
      desc_count: "1024"                                     
      prio: "1"     
      queues: "42, 43, 44, 45, 46" 
    sys_clk: "1720"
    ifc_clk: "1200"
    mac_clk: "1340"

  devports:
  - id: "0"
    sysport: "1000"
    type: "cpu"
  - fec: "KPFEC"
    id: "241"
    lanes: "0:8"
    serdes_group: "30"
    speed: "400G"
    sysport: "241"
    type: "eth"
  - fec: "KPFEC"
    id: "249"
    lanes: "0:8"
    serdes_group: "31"
    speed: "400G"
    sysport: "249"
    type: "eth"
  - fec: "KPFEC"
    id: "225"
    lanes: "0:8"
    serdes_group: "28"
    speed: "400G"
    sysport: "225"
    type: "eth"
  - fec: "KPFEC"
    id: "233"
    lanes: "0:8"
    serdes_group: "29"
    speed: "400G"
    sysport: "233"
    type: "eth"
  - fec: "KPFEC"
    id: "217"
    lanes: "0:8"
    serdes_group: "27"
    speed: "400G"
    sysport: "217"
    type: "eth"
  - fec: "KPFEC"
    id: "209"
    lanes: "0:8"
    serdes_group: "26"
    speed: "400G"
    sysport: "209"
    type: "eth"
  - fec: "KPFEC"
    id: "201"
    lanes: "0:8"
    serdes_group: "25"
    speed: "400G"
    sysport: "201"
    type: "eth"
  - fec: "KPFEC"
    id: "193"
    lanes: "0:8"
    serdes_group: "24"
    speed: "400G"
    sysport: "193"
    type: "eth"
  - fec: "KPFEC"
    id: "185"
    lanes: "0:8"
    serdes_group: "23"
    speed: "400G"
    sysport: "185"
    type: "eth"
  - fec: "KPFEC"
    id: "177"
    lanes: "0:8"
    serdes_group: "22"
    speed: "400G"
    sysport: "177"
    type: "eth"
  - fec: "KPFEC"
    id: "169"
    lanes: "0:8"
    serdes_group: "21"
    speed: "400G"
    sysport: "169"
    type: "eth"
  - fec: "KPFEC"
    id: "161"
    lanes: "0:8"
    serdes_group: "20"
    speed: "400G"
    sysport: "161"
    type: "eth"
  - fec: "KPFEC"
    id: "153"
    lanes: "0:8"
    serdes_group: "19"
    speed: "400G"
    sysport: "153"
    type: "eth"
  - fec: "KPFEC"
    id: "145"
    lanes: "0:8"
    serdes_group: "18"
    speed: "400G"
    sysport: "145"
    type: "eth"
  - fec: "KPFEC"
    id: "137"
    lanes: "0:8"
    serdes_group: "17"
    speed: "400G"
    sysport: "137"
    type: "eth"
  - fec: "KPFEC"
    id: "129"
    lanes: "0:8"
    serdes_group: "16"
    speed: "400G"
    sysport: "129"
    type: "eth"
  - fec: "KPFEC"
    id: "121"
    lanes: "0:8"
    serdes_group: "15"
    speed: "400G"
    sysport: "121"
    type: "eth"
  - fec: "KPFEC"
    id: "113"
    lanes: "0:8"
    serdes_group: "14"
    speed: "400G"
    sysport: "113"
    type: "eth"
  - fec: "KPFEC"
    id: "105"
    lanes: "0:8"
    serdes_group: "13"
    speed: "400G"
    sysport: "105"
    type: "eth"
  - fec: "KPFEC"
    id: "97"
    lanes: "0:8"
    serdes_group: "12"
    speed: "400G"
    sysport: "97"
    type: "eth"
  - fec: "KPFEC"
    id: "89"
    lanes: "0:8"
    serdes_group: "11"
    speed: "400G"
    sysport: "89"
    type: "eth"
  - fec: "KPFEC"
    id: "81"
    lanes: "0:8"
    serdes_group: "10"
    speed: "400G"
    sysport: "81"
    type: "eth"
  - fec: "KPFEC"
    id: "73"
    lanes: "0:8"
    serdes_group: "9"
    speed: "400G"
    sysport: "73"
    type: "eth"
  - fec: "KPFEC"
    id: "65"
    lanes: "0:8"
    serdes_group: "8"
    speed: "400G"
    sysport: "65"
    type: "eth"
  - fec: "KPFEC"
    id: "57"
    lanes: "0:8"
    serdes_group: "7"
    speed: "400G"
    sysport: "57"
    type: "eth"
  - fec: "KPFEC"
    id: "49"
    lanes: "0:8"
    serdes_group: "6"
    speed: "400G"
    sysport: "49"
    type: "eth"
  - fec: "KPFEC"
    id: "41"
    lanes: "0:8"
    serdes_group: "5"
    speed: "400G"
    sysport: "41"
    type: "eth"
  - fec: "KPFEC"
    id: "33"
    lanes: "0:8"
    serdes_group: "4"
    speed: "400G"
    sysport: "33"
    type: "eth"
  - fec: "KPFEC"
    id: "25"
    lanes: "0:8"
    serdes_group: "3"
    speed: "400G"
    sysport: "25"
    type: "eth"
  - fec: "KPFEC"
    id: "17"
    lanes: "0:8"
    serdes_group: "2"
    speed: "400G"
    sysport: "17"
    type: "eth"
  - fec: "KPFEC"
    id: "9"
    lanes: "0:8"
    serdes_group: "1"
    speed: "400G"
    sysport: "9"
    type: "eth"
  - fec: "KPFEC"
    id: "1"
    lanes: "0:8"
    serdes_group: "0"
    speed: "400G"
    sysport: "1"
    type: "eth"
  - fec: "NONE"
    id: "257"
    lanes: "0:1"
    serdes_group: "32"
    sysport: "257"
    type: "mgmt 0"
  - fec: "NONE"
    id: "258"
    lanes: "1:1"
    serdes_group: "32"
    sysport: "258"
    type: "mgmt 1"
  isg:
  - id: "0"
    tx_polarity: "10100000"
    rx_polarity: "11111011"
    lane_swap: "37250416"
  - id: "1"
    tx_polarity: "01010011"
    rx_polarity: "00000100"
    lane_swap: "52407613"
  - id: "2"
    tx_polarity: "11010001"
    rx_polarity: "01111100"
    lane_swap: "06153427"
  - id: "3"
    tx_polarity: "00100000"
    rx_polarity: "10001001"
    lane_swap: "74501263"
  - id: "4"
    tx_polarity: "10100000"
    rx_polarity: "11101000"
    lane_swap: "05471632"
  - id: "5"
    tx_polarity: "00010100"
    rx_polarity: "00111100"
    lane_swap: "72604351"
  - id: "6"
    tx_polarity: "11011001"
    rx_polarity: "00011001"
    lane_swap: "16340725"
  - id: "7"
    tx_polarity: "11010000"
    rx_polarity: "11000010"
    lane_swap: "70615324"
  - id: "8"
    tx_polarity: "00111101"
    rx_polarity: "11011000"
    lane_swap: "25074613"
  - id: "9"
    tx_polarity: "00001010"
    rx_polarity: "01000011"
    lane_swap: "32706451"
  - id: "10"
    tx_polarity: "00100010"
    rx_polarity: "01001011"
    lane_swap: "07162543"
  - id: "11"
    tx_polarity: "01101001"
    rx_polarity: "11110001"
    lane_swap: "41706253"
  - id: "12"
    tx_polarity: "11001000"
    rx_polarity: "11000011"
    lane_swap: "07136524"
  - id: "13"
    tx_polarity: "01100001"
    rx_polarity: "10010000"
    lane_swap: "73506412"
  - id: "14"
    tx_polarity: "01010001"
    rx_polarity: "10110110"
    lane_swap: "26143705"
  - id: "15"
    tx_polarity: "00001000"
    rx_polarity: "11101100"
    lane_swap: "51602437"
  - id: "16"
    tx_polarity: "00010000"
    rx_polarity: "11101011"
    lane_swap: "45076312"
  - id: "17"
    tx_polarity: "01011000"
    rx_polarity: "00000000"
    lane_swap: "50642371"
  - id: "18"
    tx_polarity: "01010100"
    rx_polarity: "00011001"
    lane_swap: "07436125"
  - id: "19"
    tx_polarity: "00011010"
    rx_polarity: "01001011"
    lane_swap: "61734250"
  - id: "20"
    tx_polarity: "00111110"
    rx_polarity: "10011100"
    lane_swap: "04275631"
  - id: "21"
    tx_polarity: "10110100"
    rx_polarity: "01110110"
    lane_swap: "41620573"
  - id: "22"
    tx_polarity: "01100110"
    rx_polarity: "10010000"
    lane_swap: "17240635"
  - id: "23"
    tx_polarity: "01010000"
    rx_polarity: "11110101"
    lane_swap: "52704631"
  - id: "24"
    tx_polarity: "00010001"
    rx_polarity: "10100100"
    lane_swap: "16253704"
  - id: "25"
    tx_polarity: "01000101"
    rx_polarity: "00010000"
    lane_swap: "53607241"
  - id: "26"
    tx_polarity: "00110101"
    rx_polarity: "11101110"
    lane_swap: "16074325"
  - id: "27"
    tx_polarity: "10000111"
    rx_polarity: "01011110"
    lane_swap: "75604231"
  - id: "28"
    tx_polarity: "01010100"
    rx_polarity: "01010101"
    lane_swap: "70614235"
  - id: "29"
    tx_polarity: "01010001"
    rx_polarity: "01000001"
    lane_swap: "24610537"
  - id: "30"
    tx_polarity: "01101011"
    rx_polarity: "01010011"
    lane_swap: "70614352"
  - id: "31"
    tx_polarity: "01101001"
    rx_polarity: "10100000"
    lane_swap: "34250716"
  - id: "32"
    tx_polarity: "00000000"
    rx_polarity: "00000000"
    lane_swap: "01234567"
