ifcs:
  options:
    log_level: "info"
nodes:
- node_id: "0"
  options:
    sku: "configs/sku/innovium.55200"
    netdev:
    - auto_create: "no"
      multi_interface: "yes"
    buffer_management_mode: "api_driven"
    max_lossless_tc: "2"
    skip_pll_check: "false"
    ilpm_enable: "1"
    forward_profile: "IFCS_FORWARD_PROFILE_ID_PROFILE_E"
    mac_clk: "750"
    sys_clk: "975"
    ifc_clk: "525"
    txring:
    - txring_id: "0"
      desc_count: "1024"
      prio: "1"
      netdev: "true"
    - txring_id: "1"
      desc_count: "1024"
      prio: "1"
      netdev: "true"
    - txring_id: "2"
      desc_count: "1024"
      prio: "1"
      netdev: "true"
    - txring_id: "3"
      desc_count: "1024"
      prio: "1"
      netdev: "true"
    rxring:
    - rxring_id: "0"                                         
      desc_count: "1024"                                     
      prio: "1"     
      netdev: "true"      
      queues: "0, 3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39"  
    - rxring_id: "1"                                         
      desc_count: "1024"                                     
      prio: "1"    
      netdev: "true"      
      queues: "1, 4, 7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40"  
    - rxring_id: "2"                                         
      desc_count: "1024"                                     
      prio: "1"
      netdev: "true"      
      queues: "2, 5, 8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 47" 
    - rxring_id: "3"                                         
      desc_count: "1024"                                     
      prio: "1"     
      queues: "42, 43, 44, 45, 46" 
  devports:
  - id: "0"
    sysport: "129"
    type: "cpu"
  - id: "113"
    fec: "KRFEC"
    lanes: "0:1"
    serdes_group: "14"
    speed: "25G"
    sysport: "113"
    type: "eth"
  - id: "114"
    fec: "KRFEC"
    lanes: "1:1"
    serdes_group: "14"
    speed: "25G"
    sysport: "114"
    type: "eth"
  - id: "115"
    fec: "KRFEC"
    lanes: "2:1"
    serdes_group: "14"
    speed: "25G"
    sysport: "115"
    type: "eth"
  - id: "116"
    fec: "KRFEC"
    lanes: "3:1"
    serdes_group: "14"
    speed: "25G"
    sysport: "116"
    type: "eth"
  - id: "117"
    fec: "KRFEC"
    lanes: "4:1"
    serdes_group: "14"
    speed: "25G"
    sysport: "117"
    type: "eth"
  - id: "105"
    fec: "KRFEC"
    lanes: "0:1"
    serdes_group: "13"
    speed: "25G"
    sysport: "105"
    type: "eth"
  - id: "106"
    fec: "KRFEC"
    lanes: "1:1"
    serdes_group: "13"
    speed: "25G"
    sysport: "106"
    type: "eth"
  - id: "107"
    fec: "KRFEC"
    lanes: "2:1"
    serdes_group: "13"
    speed: "25G"
    sysport: "107"
    type: "eth"
  - id: "108"
    fec: "KRFEC"
    lanes: "3:1"
    serdes_group: "13"
    speed: "25G"
    sysport: "108"
    type: "eth"
  - id: "109"
    fec: "KRFEC"
    lanes: "4:1"
    serdes_group: "13"
    speed: "25G"
    sysport: "109"
    type: "eth"
  - id: "110"
    fec: "KRFEC"
    lanes: "5:1"
    serdes_group: "13"
    speed: "25G"
    sysport: "110"
    type: "eth"
  - id: "111"
    fec: "KRFEC"
    lanes: "6:1"
    serdes_group: "13"
    speed: "25G"
    sysport: "111"
    type: "eth"
  - id: "112"
    fec: "KRFEC"
    lanes: "7:1"
    serdes_group: "13"
    speed: "25G"
    sysport: "112"
    type: "eth"
  - id: "89"
    fec: "KRFEC"
    lanes: "0:1"
    serdes_group: "11"
    speed: "25G"
    sysport: "89"
    type: "eth"
  - id: "90"
    fec: "KRFEC"
    lanes: "1:1"
    serdes_group: "11"
    speed: "25G"
    sysport: "90"
    type: "eth"
  - id: "91"
    fec: "KRFEC"
    lanes: "2:1"
    serdes_group: "11"
    speed: "25G"
    sysport: "91"
    type: "eth"
  - id: "92"
    fec: "KRFEC"
    lanes: "3:1"
    serdes_group: "11"
    speed: "25G"
    sysport: "92"
    type: "eth"
  - id: "93"
    fec: "KRFEC"
    lanes: "4:1"
    serdes_group: "11"
    speed: "25G"
    sysport: "93"
    type: "eth"
  - id: "94"
    fec: "KRFEC"
    lanes: "5:1"
    serdes_group: "11"
    speed: "25G"
    sysport: "94"
    type: "eth"
  - id: "95"
    fec: "KRFEC"
    lanes: "6:1"
    serdes_group: "11"
    speed: "25G"
    sysport: "95"
    type: "eth"
  - id: "96"
    fec: "KRFEC"
    lanes: "7:1"
    serdes_group: "11"
    speed: "25G"
    sysport: "96"
    type: "eth"
  - id: "118"
    fec: "KRFEC"
    lanes: "5:1"
    serdes_group: "14"
    speed: "25G"
    sysport: "118"
    type: "eth"
  - id: "119"
    fec: "KRFEC"
    lanes: "6:1"
    serdes_group: "14"
    speed: "25G"
    sysport: "119"
    type: "eth"
  - id: "120"
    fec: "KRFEC"
    lanes: "7:1"
    serdes_group: "14"
    speed: "25G"
    sysport: "120"
    type: "eth"
  - id: "41"
    fec: "KRFEC"
    lanes: "0:1"
    serdes_group: "5"
    speed: "25G"
    sysport: "41"
    type: "eth"
  - id: "42"
    fec: "KRFEC"
    lanes: "1:1"
    serdes_group: "5"
    speed: "25G"
    sysport: "42"
    type: "eth"
  - id: "43"
    fec: "KRFEC"
    lanes: "2:1"
    serdes_group: "5"
    speed: "25G"
    sysport: "43"
    type: "eth"
  - id: "44"
    fec: "KRFEC"
    lanes: "3:1"
    serdes_group: "5"
    speed: "25G"
    sysport: "44"
    type: "eth"
  - id: "45"
    fec: "KRFEC"
    lanes: "4:1"
    serdes_group: "5"
    speed: "25G"
    sysport: "45"
    type: "eth"
  - id: "46"
    fec: "KRFEC"
    lanes: "5:1"
    serdes_group: "5"
    speed: "25G"
    sysport: "46"
    type: "eth"
  - id: "47"
    fec: "KRFEC"
    lanes: "6:1"
    serdes_group: "5"
    speed: "25G"
    sysport: "47"
    type: "eth"
  - id: "48"
    fec: "KRFEC"
    lanes: "7:1"
    serdes_group: "5"
    speed: "25G"
    sysport: "48"
    type: "eth"
  - id: "25"
    fec: "KRFEC"
    lanes: "0:1"
    serdes_group: "3"
    speed: "25G"
    sysport: "25"
    type: "eth"
  - id: "26"
    fec: "KRFEC"
    lanes: "1:1"
    serdes_group: "3"
    speed: "25G"
    sysport: "26"
    type: "eth"
  - id: "27"
    fec: "KRFEC"
    lanes: "2:1"
    serdes_group: "3"
    speed: "25G"
    sysport: "27"
    type: "eth"
  - id: "28"
    fec: "KRFEC"
    lanes: "3:1"
    serdes_group: "3"
    speed: "25G"
    sysport: "28"
    type: "eth"
  - id: "29"
    fec: "KRFEC"
    lanes: "4:1"
    serdes_group: "3"
    speed: "25G"
    sysport: "29"
    type: "eth"
  - id: "30"
    fec: "KRFEC"
    lanes: "5:1"
    serdes_group: "3"
    speed: "25G"
    sysport: "30"
    type: "eth"
  - id: "31"
    fec: "KRFEC"
    lanes: "6:1"
    serdes_group: "3"
    speed: "25G"
    sysport: "31"
    type: "eth"
  - id: "32"
    fec: "KRFEC"
    lanes: "7:1"
    serdes_group: "3"
    speed: "25G"
    sysport: "32"
    type: "eth"
  - id: "17"
    fec: "KRFEC"
    lanes: "0:1"
    serdes_group: "2"
    speed: "25G"
    sysport: "17"
    type: "eth"
  - id: "18"
    fec: "KRFEC"
    lanes: "1:1"
    serdes_group: "2"
    speed: "25G"
    sysport: "18"
    type: "eth"
  - id: "19"
    fec: "KRFEC"
    lanes: "2:1"
    serdes_group: "2"
    speed: "25G"
    sysport: "19"
    type: "eth"
  - id: "20"
    fec: "KRFEC"
    lanes: "3:1"
    serdes_group: "2"
    speed: "25G"
    sysport: "20"
    type: "eth"
  - id: "21"
    fec: "KRFEC"
    lanes: "4:1"
    serdes_group: "2"
    speed: "25G"
    sysport: "21"
    type: "eth"
  - id: "22"
    fec: "KRFEC"
    lanes: "5:1"
    serdes_group: "2"
    speed: "25G"
    sysport: "22"
    type: "eth"
  - id: "23"
    fec: "KRFEC"
    lanes: "6:1"
    serdes_group: "2"
    speed: "25G"
    sysport: "23"
    type: "eth"
  - id: "24"
    fec: "KRFEC"
    lanes: "7:1"
    serdes_group: "2"
    speed: "25G"
    sysport: "24"
    type: "eth"
  - id: "73"
    fec: "KRFEC"
    lanes: "0:4"
    serdes_group: "9"
    speed: "100G"
    sysport: "73"
    type: "eth"
  - id: "77"
    fec: "KRFEC"
    lanes: "4:4"
    serdes_group: "9"
    speed: "100G"
    sysport: "77"
    type: "eth"
  - id: "65"
    fec: "KRFEC"
    lanes: "0:4"
    serdes_group: "8"
    speed: "100G"
    sysport: "65"
    type: "eth"
  - id: "69"
    fec: "KRFEC"
    lanes: "4:4"
    serdes_group: "8"
    speed: "100G"
    sysport: "69"
    type: "eth"
  - id: "9"
    fec: "KRFEC"
    lanes: "0:4"
    serdes_group: "1"
    speed: "100G"
    sysport: "9"
    type: "eth"
  - id: "13"
    fec: "KRFEC"
    lanes: "4:4"
    serdes_group: "1"
    speed: "100G"
    sysport: "13"
    type: "eth"
  - id: "1"
    fec: "KRFEC"
    lanes: "0:4"
    serdes_group: "0"
    speed: "100G"
    sysport: "1"
    type: "eth"
  - id: "5"
    fec: "KRFEC"
    lanes: "4:4"
    serdes_group: "0"
    speed: "100G"
    sysport: "5"
    type: "eth"
#  Aux ports to be enabled later
#  - id: "33"
#    fec: "NONE"
#    lanes: "0:1"
#    serdes_group: "16"
#    speed: "10G"
#    sysport: "33"
#    type: "mgmt 0"
#  - id: "34"
#    fec: "NONE"
#    lanes: "1:1"
#    serdes_group: "16"
#    speed: "10G"
#    sysport: "34"
#    type: "mgmt 1"
  isg:
  - id: "0"
    lane_swap: "10325674"  
    rx_polarity: "00000110"    
    tx_polarity: "00010001"
    pre1: "-3, -3, -3, -3, -3, -3, -3, -3"
    main: "20, 20, 20, 20, 20, 20, 20, 20"    
  - id: "1"
    lane_swap: "12305476"  
    rx_polarity: "01111110"    
    tx_polarity: "10111101"
    pre1: "-3, -3, -3, -3, -3, -3, -3, -3"
    main: "20, 20, 20, 20, 20, 20, 20, 20"    
  - id: "2"
    lane_swap: "20416375"  
    rx_polarity: "00101011"    
    tx_polarity: "01100011"
    pre1: "-3, -3, -3, -3, -3, -3, -3, -3"
    main: "20, 20, 20, 20, 20, 20, 20, 20"    
  - id: "3"
    lane_swap: "01234576"  
    rx_polarity: "01010111"    
    tx_polarity: "10001110"
    pre1: "-3, -3, -3, -3, -3, -3, -3, -3"
    main: "20, 20, 20, 20, 20, 20, 20, 20"    
  - id: "4"
    lane_swap: "01234567"
    rx_polarity: "00000000"
    tx_polarity: "10100000"
    pre1: "-3, -3, -3, -3, -3, -3, -3, -3"
    main: "20, 20, 20, 20, 20, 20, 20, 20"    
  - id: "5"
    lane_swap: "13250467"
    rx_polarity: "10100110"    
    tx_polarity: "10101001"
    pre1: "-3, -3, -3, -3, -3, -3, -3, -3"
    main: "20, 20, 20, 20, 20, 20, 20, 20"    
  - id: "6"
    lane_swap: "01234567"
    rx_polarity: "00000000"
    tx_polarity: "10100000"
    pre1: "-3, -3, -3, -3, -3, -3, -3, -3"
    main: "20, 20, 20, 20, 20, 20, 20, 20"    
  - id: "7"
    lane_swap: "01234567"
    rx_polarity: "00000000"
    tx_polarity: "10100000"
    pre1: "-3, -3, -3, -3, -3, -3, -3, -3"
    main: "20, 20, 20, 20, 20, 20, 20, 20"    
  - id: "8"
    lane_swap: "03214576"  
    rx_polarity: "01110010"
    tx_polarity: "01101010"
    pre1: "-3, -3, -3, -3, -3, -3, -3, -3"
    main: "20, 20, 20, 20, 20, 20, 20, 20"    
  - id: "9"
    lane_swap: "30217456"  
    rx_polarity: "00000111"     
    tx_polarity: "01010001"
    pre1: "-3, -3, -3, -3, -3, -3, -3, -3"
    main: "20, 20, 20, 20, 20, 20, 20, 20"    
  - id: "10"
    lane_swap: "01234567"
    rx_polarity: "00000000"
    tx_polarity: "10100000"
    pre1: "-3, -3, -3, -3, -3, -3, -3, -3"
    main: "20, 20, 20, 20, 20, 20, 20, 20"    
  - id: "11"
    lane_swap: "76543201"  
    rx_polarity: "10010100"       
    tx_polarity: "11010010"
    pre1: "-3, -3, -3, -3, -3, -3, -3, -3"
    main: "20, 20, 20, 20, 20, 20, 20, 20"    
  - id: "12"
    lane_swap: "01234567"
    rx_polarity: "00000000"
    tx_polarity: "10100000"
    pre1: "-3, -3, -3, -3, -3, -3, -3, -3"
    main: "20, 20, 20, 20, 20, 20, 20, 20"    
  - id: "13"
    lane_swap: "75614320"  
    rx_polarity: "01101111"
    tx_polarity: "11010111"
    pre1: "-3, -3, -3, -3, -3, -3, -3, -3"
    main: "20, 20, 20, 20, 20, 20, 20, 20"    
  - id: "14"
    lane_swap: "52476013"  
    rx_polarity: "01011011"    
    tx_polarity: "00011000"
    pre1: "-3, -3, -3, -3, -3, -3, -3, -3"
    main: "20, 20, 20, 20, 20, 20, 20, 20"    
  - id: "15"
    lane_swap: "01234567"
    rx_polarity: "00000000"
    tx_polarity: "10100000"
    pre1: "-3, -3, -3, -3, -3, -3, -3, -3"
    main: "20, 20, 20, 20, 20, 20, 20, 20"    
