ifcs:
  options:
    log_level: "info"
nodes:
- node_id: "0"
  options:
    sku: "configs/sku/innovium.77700_B"
    netdev:
    - auto_create: "no"
      multi_interface: "yes"
    buffer_management_mode: "api_driven"
    max_lossless_tc: "2"
    txring:
    - txring_id: "0"
      desc_count: "1024"
      prio: "1"
      netdev: "true"
    - txring_id: "1"
      desc_count: "1024"
      prio: "1"
      netdev: "true"
    - txring_id: "2"
      desc_count: "1024"
      prio: "1"
      netdev: "true"
    - txring_id: "3"
      desc_count: "1024"
      prio: "1"
      netdev: "true"
    rxring:
    - rxring_id: "0"
      desc_count: "1024"
      prio: "1"
      netdev: "true"
      queues: "0, 4, 8, 12, 16, 20, 24, 28, 32, 36, 40, 44"
    - rxring_id: "1"
      desc_count: "1024"
      prio: "1"
      netdev: "true"
      queues: "1, 5, 9, 13, 17, 21, 25, 29, 33, 37, 41, 45"
    - rxring_id: "2"
      desc_count: "1024"
      prio: "1"
      netdev: "true"
      queues: "2, 6, 10, 14, 18, 22, 26, 30, 34, 38, 42, 46"
    - rxring_id: "3"
      desc_count: "1024"
      prio: "1"
      netdev: "true"
      queues: "3, 7, 11, 15, 19, 23, 27, 31, 35, 39, 43, 47"
    sys_clk: "1720"
    ifc_clk: "1200"
    mac_clk: "1340"

  devports:
  - id: "0"
    sysport: "1000"
    type: "cpu"
  - fec: "KRFEC"
    id: "249"
    lanes: "0:4"
    serdes_group: "31"
    speed: "100G"
    sysport: "249"
    type: "eth"
  - fec: "KRFEC"
    id: "253"
    lanes: "4:4"
    serdes_group: "31"
    speed: "100G"
    sysport: "253"
    type: "eth"
  - fec: "KRFEC"
    id: "241"
    lanes: "0:4"
    serdes_group: "30"
    speed: "100G"
    sysport: "241"
    type: "eth"
  - fec: "KRFEC"
    id: "245"
    lanes: "4:4"
    serdes_group: "30"
    speed: "100G"
    sysport: "245"
    type: "eth"
  - fec: "KRFEC"
    id: "233"
    lanes: "0:4"
    serdes_group: "29"
    speed: "100G"
    sysport: "233"
    type: "eth"
  - fec: "KRFEC"
    id: "237"
    lanes: "4:4"
    serdes_group: "29"
    speed: "100G"
    sysport: "237"
    type: "eth"
  - fec: "KRFEC"
    id: "225"
    lanes: "0:4"
    serdes_group: "28"
    speed: "100G"
    sysport: "225"
    type: "eth"
  - fec: "KRFEC"
    id: "229"
    lanes: "4:4"
    serdes_group: "28"
    speed: "100G"
    sysport: "229"
    type: "eth"
  - fec: "KRFEC"
    id: "217"
    lanes: "0:4"
    serdes_group: "27"
    speed: "100G"
    sysport: "217"
    type: "eth"
  - fec: "KRFEC"
    id: "221"
    lanes: "4:4"
    serdes_group: "27"
    speed: "100G"
    sysport: "221"
    type: "eth"
  - fec: "KRFEC"
    id: "209"
    lanes: "0:4"
    serdes_group: "26"
    speed: "100G"
    sysport: "209"
    type: "eth"
  - fec: "KRFEC"
    id: "213"
    lanes: "4:4"
    serdes_group: "26"
    speed: "100G"
    sysport: "213"
    type: "eth"
  - fec: "KRFEC"
    id: "201"
    lanes: "0:4"
    serdes_group: "25"
    speed: "100G"
    sysport: "201"
    type: "eth"
  - fec: "KRFEC"
    id: "205"
    lanes: "4:4"
    serdes_group: "25"
    speed: "100G"
    sysport: "205"
    type: "eth"
  - fec: "KRFEC"
    id: "193"
    lanes: "0:4"
    serdes_group: "24"
    speed: "100G"
    sysport: "193"
    type: "eth"
  - fec: "KRFEC"
    id: "197"
    lanes: "4:4"
    serdes_group: "24"
    speed: "100G"
    sysport: "197"
    type: "eth"
  - fec: "KRFEC"
    id: "185"
    lanes: "0:4"
    serdes_group: "23"
    speed: "100G"
    sysport: "185"
    type: "eth"
  - fec: "KRFEC"
    id: "189"
    lanes: "4:4"
    serdes_group: "23"
    speed: "100G"
    sysport: "189"
    type: "eth"
  - fec: "KRFEC"
    id: "177"
    lanes: "0:4"
    serdes_group: "22"
    speed: "100G"
    sysport: "177"
    type: "eth"
  - fec: "KRFEC"
    id: "181"
    lanes: "4:4"
    serdes_group: "22"
    speed: "100G"
    sysport: "181"
    type: "eth"
  - fec: "KRFEC"
    id: "169"
    lanes: "0:4"
    serdes_group: "21"
    speed: "100G"
    sysport: "169"
    type: "eth"
  - fec: "KRFEC"
    id: "173"
    lanes: "4:4"
    serdes_group: "21"
    speed: "100G"
    sysport: "173"
    type: "eth"
  - fec: "KRFEC"
    id: "161"
    lanes: "0:4"
    serdes_group: "20"
    speed: "100G"
    sysport: "161"
    type: "eth"
  - fec: "KRFEC"
    id: "165"
    lanes: "4:4"
    serdes_group: "20"
    speed: "100G"
    sysport: "165"
    type: "eth"
  - fec: "KRFEC"
    id: "153"
    lanes: "0:4"
    serdes_group: "19"
    speed: "100G"
    sysport: "153"
    type: "eth"
  - fec: "KRFEC"
    id: "157"
    lanes: "4:4"
    serdes_group: "19"
    speed: "100G"
    sysport: "157"
    type: "eth"
  - fec: "KRFEC"
    id: "145"
    lanes: "0:4"
    serdes_group: "18"
    speed: "100G"
    sysport: "145"
    type: "eth"
  - fec: "KRFEC"
    id: "149"
    lanes: "4:4"
    serdes_group: "18"
    speed: "100G"
    sysport: "149"
    type: "eth"
  - fec: "KRFEC"
    id: "137"
    lanes: "0:4"
    serdes_group: "17"
    speed: "100G"
    sysport: "137"
    type: "eth"
  - fec: "KRFEC"
    id: "141"
    lanes: "4:4"
    serdes_group: "17"
    speed: "100G"
    sysport: "141"
    type: "eth"
  - fec: "KRFEC"
    id: "129"
    lanes: "0:4"
    serdes_group: "16"
    speed: "100G"
    sysport: "129"
    type: "eth"
  - fec: "KRFEC"
    id: "133"
    lanes: "4:4"
    serdes_group: "16"
    speed: "100G"
    sysport: "133"
    type: "eth"
  - fec: "KRFEC"
    id: "121"
    lanes: "0:4"
    serdes_group: "15"
    speed: "100G"
    sysport: "121"
    type: "eth"
  - fec: "KRFEC"
    id: "125"
    lanes: "4:4"
    serdes_group: "15"
    speed: "100G"
    sysport: "125"
    type: "eth"
  - fec: "KRFEC"
    id: "113"
    lanes: "0:4"
    serdes_group: "14"
    speed: "100G"
    sysport: "113"
    type: "eth"
  - fec: "KRFEC"
    id: "117"
    lanes: "4:4"
    serdes_group: "14"
    speed: "100G"
    sysport: "117"
    type: "eth"
  - fec: "KRFEC"
    id: "97"
    lanes: "0:4"
    serdes_group: "12"
    speed: "100G"
    sysport: "97"
    type: "eth"
  - fec: "KRFEC"
    id: "101"
    lanes: "4:4"
    serdes_group: "12"
    speed: "100G"
    sysport: "101"
    type: "eth"
  - fec: "KRFEC"
    id: "105"
    lanes: "0:4"
    serdes_group: "13"
    speed: "100G"
    sysport: "105"
    type: "eth"
  - fec: "KRFEC"
    id: "109"
    lanes: "4:4"
    serdes_group: "13"
    speed: "100G"
    sysport: "109"
    type: "eth"
  - fec: "KRFEC"
    id: "81"
    lanes: "0:4"
    serdes_group: "10"
    speed: "100G"
    sysport: "81"
    type: "eth"
  - fec: "KRFEC"
    id: "85"
    lanes: "4:4"
    serdes_group: "10"
    speed: "100G"
    sysport: "85"
    type: "eth"
  - fec: "KRFEC"
    id: "89"
    lanes: "0:4"
    serdes_group: "11"
    speed: "100G"
    sysport: "89"
    type: "eth"
  - fec: "KRFEC"
    id: "93"
    lanes: "4:4"
    serdes_group: "11"
    speed: "100G"
    sysport: "93"
    type: "eth"
  - fec: "KRFEC"
    id: "65"
    lanes: "0:4"
    serdes_group: "8"
    speed: "100G"
    sysport: "65"
    type: "eth"
  - fec: "KRFEC"
    id: "69"
    lanes: "4:4"
    serdes_group: "8"
    speed: "100G"
    sysport: "69"
    type: "eth"
  - fec: "KRFEC"
    id: "73"
    lanes: "0:4"
    serdes_group: "9"
    speed: "100G"
    sysport: "73"
    type: "eth"
  - fec: "KRFEC"
    id: "77"
    lanes: "4:4"
    serdes_group: "9"
    speed: "100G"
    sysport: "77"
    type: "eth"
  - fec: "KRFEC"
    id: "49"
    lanes: "0:4"
    serdes_group: "6"
    speed: "100G"
    sysport: "49"
    type: "eth"
  - fec: "KRFEC"
    id: "53"
    lanes: "4:4"
    serdes_group: "6"
    speed: "100G"
    sysport: "53"
    type: "eth"
  - fec: "KRFEC"
    id: "57"
    lanes: "0:4"
    serdes_group: "7"
    speed: "100G"
    sysport: "57"
    type: "eth"
  - fec: "KRFEC"
    id: "61"
    lanes: "4:4"
    serdes_group: "7"
    speed: "100G"
    sysport: "61"
    type: "eth"
  - fec: "KRFEC"
    id: "33"
    lanes: "0:4"
    serdes_group: "4"
    speed: "100G"
    sysport: "33"
    type: "eth"
  - fec: "KRFEC"
    id: "37"
    lanes: "4:4"
    serdes_group: "4"
    speed: "100G"
    sysport: "37"
    type: "eth"
  - fec: "KRFEC"
    id: "41"
    lanes: "0:4"
    serdes_group: "5"
    speed: "100G"
    sysport: "41"
    type: "eth"
  - fec: "KRFEC"
    id: "45"
    lanes: "4:4"
    serdes_group: "5"
    speed: "100G"
    sysport: "45"
    type: "eth"
  - fec: "KRFEC"
    id: "17"
    lanes: "0:4"
    serdes_group: "2"
    speed: "100G"
    sysport: "17"
    type: "eth"
  - fec: "KRFEC"
    id: "21"
    lanes: "4:4"
    serdes_group: "2"
    speed: "100G"
    sysport: "21"
    type: "eth"
  - fec: "KRFEC"
    id: "25"
    lanes: "0:4"
    serdes_group: "3"
    speed: "100G"
    sysport: "25"
    type: "eth"
  - fec: "KRFEC"
    id: "29"
    lanes: "4:4"
    serdes_group: "3"
    speed: "100G"
    sysport: "29"
    type: "eth"
  - fec: "KRFEC"
    id: "1"
    lanes: "0:4"
    serdes_group: "0"
    speed: "100G"
    sysport: "1"
    type: "eth"
  - fec: "KRFEC"
    id: "5"
    lanes: "4:4"
    serdes_group: "0"
    speed: "100G"
    sysport: "5"
    type: "eth"
  - fec: "KRFEC"
    id: "9"
    lanes: "0:4"
    serdes_group: "1"
    speed: "100G"
    sysport: "9"
    type: "eth"
  - fec: "KRFEC"
    id: "13"
    lanes: "4:4"
    serdes_group: "1"
    speed: "100G"
    sysport: "13"
    type: "eth"
  - fec: "NONE"
    id: "257"
    lanes: "0:1"
    serdes_group: "32"
    speed: "10G"
    sysport: "257"
    type: "mgmt 0"
  - fec: "NONE"
    id: "258"
    lanes: "1:1"
    serdes_group: "32"
    speed: "10G"
    sysport: "258"
    type: "mgmt 1"
  isg:
  - id: "0"
    tx_polarity: "01010101"
    rx_polarity: "01100000"
    lane_swap: "23641075"
  - id: "1"
    tx_polarity: "10110000"
    rx_polarity: "11111111"
    lane_swap: "64317520"
  - id: "2"
    tx_polarity: "00000000"
    rx_polarity: "00000011"
    lane_swap: "63147520"
  - id: "3"
    tx_polarity: "01101000"
    rx_polarity: "00001110"
    lane_swap: "31572046"
  - id: "4"
    tx_polarity: "00111000"
    rx_polarity: "00001000"
    lane_swap: "46105732"
  - id: "5"
    tx_polarity: "10111111"
    rx_polarity: "11101000"
    lane_swap: "27153604"
  - id: "6"
    tx_polarity: "01101110"
    rx_polarity: "00001101"
    lane_swap: "46503721"
  - id: "7"
    tx_polarity: "01000100"
    rx_polarity: "10000101"
    lane_swap: "03671245"
  - id: "8"
    tx_polarity: "01110101"
    rx_polarity: "00010000"
    lane_swap: "12640375"
  - id: "9"
    tx_polarity: "01011100"
    rx_polarity: "11001111"
    lane_swap: "02561347"
  - id: "10"
    tx_polarity: "01110110"
    rx_polarity: "11000000"
    lane_swap: "12740365"
  - id: "11"
    tx_polarity: "00111000"
    rx_polarity: "00010111"
    lane_swap: "01572436"
  - id: "12"
    tx_polarity: "00001111"
    rx_polarity: "10111001"
    lane_swap: "54320176"
  - id: "13"
    tx_polarity: "10011101"
    rx_polarity: "00111011"
    lane_swap: "26153704"
  - id: "14"
    tx_polarity: "00110000"
    rx_polarity: "11010000"
    lane_swap: "37452601"
  - id: "15"
    tx_polarity: "11100010"
    rx_polarity: "01110011"
    lane_swap: "51370462"
  - id: "16"
    tx_polarity: "10111010"
    rx_polarity: "11010011"
    lane_swap: "36152704"
  - id: "17"
    tx_polarity: "01011101"
    rx_polarity: "00110001"
    lane_swap: "45621073"
  - id: "18"
    tx_polarity: "11011111"
    rx_polarity: "11001011"
    lane_swap: "26143705"
  - id: "19"
    tx_polarity: "00100110"
    rx_polarity: "00001001"
    lane_swap: "42730165"
  - id: "20"
    tx_polarity: "10011011"
    rx_polarity: "01101101"
    lane_swap: "54217603"
  - id: "21"
    tx_polarity: "00101110"
    rx_polarity: "10111111"
    lane_swap: "26031745"
  - id: "22"
    tx_polarity: "01001110"
    rx_polarity: "00111001"
    lane_swap: "36024715"
  - id: "23"
    tx_polarity: "10101101"
    rx_polarity: "01010011"
    lane_swap: "45621370"
  - id: "24"
    tx_polarity: "11001110"
    rx_polarity: "00011111"
    lane_swap: "65234701"
  - id: "25"
    tx_polarity: "01110001"
    rx_polarity: "01010111"
    lane_swap: "37601452"
  - id: "26"
    tx_polarity: "01000100"
    rx_polarity: "00001111"
    lane_swap: "65034721"
  - id: "27"
    tx_polarity: "10111101"
    rx_polarity: "11000101"
    lane_swap: "34501672"
  - id: "28"
    tx_polarity: "01111000"
    rx_polarity: "01110110"
    lane_swap: "43061275"
  - id: "29"
    tx_polarity: "11110111"
    rx_polarity: "11100111"
    lane_swap: "57304621"
  - id: "30"
    tx_polarity: "10000100"
    rx_polarity: "00101111"
    lane_swap: "47125603"
  - id: "31"
    tx_polarity: "11111111"
    rx_polarity: "11100010"
    lane_swap: "13460275"
  - id: "32"
    tx_polarity: "00000000"
    rx_polarity: "00000000"
    lane_swap: "01234567"
