ifcs:
  options:
    log_level: "info"
nodes:
- node_id: "0"
  options:
    sku: "configs/sku/innovium.55610"
    netdev:
    - auto_create: "no"
      multi_interface: "yes"
    buffer_management_mode: "api_driven"
    max_lossless_tc: "2"
    skip_pll_check: "false"
    ilpm_enable: "1"
    forward_profile: "IFCS_FORWARD_PROFILE_ID_PROFILE_E"
    mac_clk: "1340"
    sys_clk: "2000"
    ifc_clk: "1000"
    txring:
    - txring_id: "0"
      desc_count: "1024"
      prio: "1"
      netdev: "true"
    - txring_id: "1"
      desc_count: "1024"
      prio: "1"
      netdev: "true"
    - txring_id: "2"
      desc_count: "1024"
      prio: "1"
      netdev: "true"
    - txring_id: "3"
      desc_count: "1024"
      prio: "1"
      netdev: "true"
    rxring:
    - rxring_id: "0"                                         
      desc_count: "1024"                                     
      prio: "1"     
      netdev: "true"      
      queues: "0, 3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39"  
    - rxring_id: "1"                                         
      desc_count: "1024"                                     
      prio: "1"    
      netdev: "true"      
      queues: "1, 4, 7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40"  
    - rxring_id: "2"                                         
      desc_count: "1024"                                     
      prio: "1"
      netdev: "true"      
      queues: "2, 5, 8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 47" 
    - rxring_id: "3"                                         
      desc_count: "1024"                                     
      prio: "1"     
      queues: "42, 43, 44, 45, 46" 
  devports:
  - id: "0"
    sysport: "1000"
    type: "cpu"
  - fec: "KPFEC"
    id: "121"
    lanes: "0:4"
    serdes_group: "15"
    speed: "200G"
    sysport: "121"
    type: "eth"
  - fec: "KPFEC"
    id: "125"
    lanes: "4:4"
    serdes_group: "15"
    speed: "200G"
    sysport: "125"
    type: "eth"
  - fec: "KPFEC"
    id: "113"
    lanes: "0:4"
    serdes_group: "14"
    speed: "200G"
    sysport: "113"
    type: "eth"
  - fec: "KPFEC"
    id: "117"
    lanes: "4:4"
    serdes_group: "14"
    speed: "200G"
    sysport: "117"
    type: "eth"
  - fec: "KPFEC"
    id: "105"
    lanes: "0:4"
    serdes_group: "13"
    speed: "200G"
    sysport: "105"
    type: "eth"
  - fec: "KPFEC"
    id: "109"
    lanes: "4:4"
    serdes_group: "13"
    speed: "200G"
    sysport: "109"
    type: "eth"
  - fec: "KPFEC"
    id: "97"
    lanes: "0:4"
    serdes_group: "12"
    speed: "200G"
    sysport: "97"
    type: "eth"
  - fec: "KPFEC"
    id: "101"
    lanes: "4:4"
    serdes_group: "12"
    speed: "200G"
    sysport: "101"
    type: "eth"
  - fec: "KPFEC"
    id: "89"
    lanes: "0:4"
    serdes_group: "11"
    speed: "200G"
    sysport: "89"
    type: "eth"
  - fec: "KPFEC"
    id: "93"
    lanes: "4:4"
    serdes_group: "11"
    speed: "200G"
    sysport: "93"
    type: "eth"
  - fec: "KPFEC"
    id: "81"
    lanes: "0:4"
    serdes_group: "10"
    speed: "200G"
    sysport: "81"
    type: "eth"
  - fec: "KPFEC"
    id: "85"
    lanes: "4:4"
    serdes_group: "10"
    speed: "200G"
    sysport: "85"
    type: "eth"
  - fec: "KPFEC"
    id: "73"
    lanes: "0:4"
    serdes_group: "9"
    speed: "200G"
    sysport: "73"
    type: "eth"
  - fec: "KPFEC"
    id: "77"
    lanes: "4:4"
    serdes_group: "9"
    speed: "200G"
    sysport: "77"
    type: "eth"
  - fec: "KPFEC"
    id: "65"
    lanes: "0:4"
    serdes_group: "8"
    speed: "200G"
    sysport: "65"
    type: "eth"
  - fec: "KPFEC"
    id: "69"
    lanes: "4:4"
    serdes_group: "8"
    speed: "200G"
    sysport: "69"
    type: "eth"
  - fec: "KPFEC"
    id: "57"
    lanes: "0:4"
    serdes_group: "7"
    speed: "200G"
    sysport: "57"
    type: "eth"
  - fec: "KPFEC"
    id: "61"
    lanes: "4:4"
    serdes_group: "7"
    speed: "200G"
    sysport: "61"
    type: "eth"
  - fec: "KPFEC"
    id: "49"
    lanes: "0:4"
    serdes_group: "6"
    speed: "200G"
    sysport: "49"
    type: "eth"
  - fec: "KPFEC"
    id: "53"
    lanes: "4:4"
    serdes_group: "6"
    speed: "200G"
    sysport: "53"
    type: "eth"
  - fec: "KPFEC"
    id: "41"
    lanes: "0:4"
    serdes_group: "5"
    speed: "200G"
    sysport: "41"
    type: "eth"
  - fec: "KPFEC"
    id: "45"
    lanes: "4:4"
    serdes_group: "5"
    speed: "200G"
    sysport: "45"
    type: "eth"
  - fec: "KPFEC"
    id: "33"
    lanes: "0:4"
    serdes_group: "4"
    speed: "200G"
    sysport: "33"
    type: "eth"
  - fec: "KPFEC"
    id: "37"
    lanes: "4:4"
    serdes_group: "4"
    speed: "200G"
    sysport: "37"
    type: "eth"
  - fec: "KPFEC"
    id: "25"
    lanes: "0:4"
    serdes_group: "3"
    speed: "200G"
    sysport: "25"
    type: "eth"
  - fec: "KPFEC"
    id: "29"
    lanes: "4:4"
    serdes_group: "3"
    speed: "200G"
    sysport: "29"
    type: "eth"
  - fec: "KPFEC"
    id: "17"
    lanes: "0:4"
    serdes_group: "2"
    speed: "200G"
    sysport: "17"
    type: "eth"
  - fec: "KPFEC"
    id: "21"
    lanes: "4:4"
    serdes_group: "2"
    speed: "200G"
    sysport: "21"
    type: "eth"
  - fec: "KPFEC"
    id: "9"
    lanes: "0:4"
    serdes_group: "1"
    speed: "200G"
    sysport: "9"
    type: "eth"
  - fec: "KPFEC"
    id: "13"
    lanes: "4:4"
    serdes_group: "1"
    speed: "200G"
    sysport: "13"
    type: "eth"
  - fec: "KPFEC"
    id: "1"
    lanes: "0:4"
    serdes_group: "0"
    speed: "200G"
    sysport: "1"
    type: "eth"
  - fec: "KPFEC"
    id: "5"
    lanes: "4:4"
    serdes_group: "0"
    speed: "200G"
    sysport: "5"
    type: "eth"
#  Aux ports to be enabled later
#  - id: "33"
#    fec: "NONE"
#    lanes: "0:1"
#    serdes_group: "16"
#    speed: "10G"
#    sysport: "33"
#    type: "mgmt 0"
#  - id: "34"
#    fec: "NONE"
#    lanes: "1:1"
#    serdes_group: "16"
#    speed: "10G"
#    sysport: "34"
#    type: "mgmt 1"
  isg:
  - id: "0"
    tx_polarity: "00001010"
    rx_polarity: "01001001"
    lane_swap: "46750132"
    pre1: "-3, -3, -3, -3, -3, -3, -3, -3"
    main: "20, 20, 20, 20, 20, 20, 20, 20"     
  - id: "1"
    tx_polarity: "00011111"
    rx_polarity: "01101001"
    lane_swap: "46752130"
    pre1: "-3, -3, -3, -3, -3, -3, -3, -3"
    main: "20, 20, 20, 20, 20, 20, 20, 20"     
  - id: "2"
    tx_polarity: "00101000"
    rx_polarity: "11110111"
    lane_swap: "57462301"
    pre1: "-3, -3, -3, -3, -3, -3, -3, -3"
    main: "20, 20, 20, 20, 20, 20, 20, 20"     
  - id: "3"
    tx_polarity: "00111101"
    rx_polarity: "00101101"
    lane_swap: "67542301"
    pre1: "-3, -3, -3, -3, -3, -3, -3, -3"
    main: "20, 20, 20, 20, 20, 20, 20, 20"     
  - id: "4"
    tx_polarity: "01110110"
    rx_polarity: "01111101"
    lane_swap: "76543021"
    pre1: "-3, -3, -3, -3, -3, -3, -3, -3"
    main: "20, 20, 20, 20, 20, 20, 20, 20"     
  - id: "5"
    tx_polarity: "00100100"
    rx_polarity: "01101010"
    lane_swap: "76542103"
    pre1: "-3, -3, -3, -3, -3, -3, -3, -3"
    main: "20, 20, 20, 20, 20, 20, 20, 20"     
  - id: "6"
    tx_polarity: "11000011"
    rx_polarity: "11110101"
    lane_swap: "45672013"
    pre1: "-3, -3, -3, -3, -3, -3, -3, -3"
    main: "20, 20, 20, 20, 20, 20, 20, 20"     
  - id: "7"
    tx_polarity: "10011101"
    rx_polarity: "11111010"
    lane_swap: "74562103"
    pre1: "-3, -3, -3, -3, -3, -3, -3, -3"
    main: "20, 20, 20, 20, 20, 20, 20, 20"     
  - id: "8"
    tx_polarity: "01001000"
    rx_polarity: "00100011"
    lane_swap: "54672301"
    pre1: "-3, -3, -3, -3, -3, -3, -3, -3"
    main: "20, 20, 20, 20, 20, 20, 20, 20"     
  - id: "9"
    tx_polarity: "11111111"
    rx_polarity: "01110111"
    lane_swap: "46750321"
    pre1: "-3, -3, -3, -3, -3, -3, -3, -3"
    main: "20, 20, 20, 20, 20, 20, 20, 20"     
  - id: "10"
    tx_polarity: "10011110"
    rx_polarity: "10110000"
    lane_swap: "67542310"
    pre1: "-3, -3, -3, -3, -3, -3, -3, -3"
    main: "20, 20, 20, 20, 20, 20, 20, 20"     
  - id: "11"
    tx_polarity: "01010010"
    rx_polarity: "10101011"
    lane_swap: "65741302"
    pre1: "-3, -3, -3, -3, -3, -3, -3, -3"
    main: "20, 20, 20, 20, 20, 20, 20, 20"     
  - id: "12"
    tx_polarity: "11010110"
    rx_polarity: "01101001"
    lane_swap: "45760321"
    pre1: "-3, -3, -3, -3, -3, -3, -3, -3"
    main: "20, 20, 20, 20, 20, 20, 20, 20"     
  - id: "13"
    tx_polarity: "01110111"
    rx_polarity: "00101000"
    lane_swap: "45670123"
    pre1: "-3, -3, -3, -3, -3, -3, -3, -3"
    main: "20, 20, 20, 20, 20, 20, 20, 20"     
  - id: "14"
    tx_polarity: "11110110"
    rx_polarity: "10111100"
    lane_swap: "67542013"    
    pre1: "-3, -3, -3, -3, -3, -3, -3, -3"
    main: "20, 20, 20, 20, 20, 20, 20, 20"     
  - id: "15"
    tx_polarity: "01011011"
    rx_polarity: "01101000"
    lane_swap: "64572103"      
    pre1: "-3, -3, -3, -3, -3, -3, -3, -3"
    main: "20, 20, 20, 20, 20, 20, 20, 20"     


