ifcs:
  options:
    log_level: "info"
nodes:
- node_id: "0"
  options:
    sd_low_power_mode_global_default: "true"
    sku: "configs/sku/innovium.77700_B"
    netdev:
    - auto_create: "no"
      multi_interface: "yes"
    buffer_management_mode: "api_driven"
    max_lossless_tc: "2"
    ilpm_enable: "1"
    forward_profile: "IFCS_FORWARD_PROFILE_ID_PROFILE_E"
    ecn_stats_enable: "1"
    pcie_attn: "10, 0, 0, 0"
    pcie_post: "10, 18, 18, 18"
    pcie_pre1: "0, 0, 0, 0"
    led_cfg_sck_rate: "0x5"
    led_refresh_precliff_timer: "0x18eec2"
    led_refresh_cliff_timer: "0x15e"
    led_cfg_pic_stream_mode: "1"
    led_refresh_tmr_ctl_enable: "1"
    txring:
    - txring_id: "0"
      desc_count: "1024"
      prio: "1"
      netdev: "true"
    - txring_id: "1"
      desc_count: "1024"
      prio: "1"
      netdev: "true"
    - txring_id: "2"
      desc_count: "1024"
      prio: "1"
      netdev: "true"
    - txring_id: "3"
      desc_count: "1024"
      prio: "1"
      netdev: "true"
    rxring:
    - rxring_id: "0"                                         
      desc_count: "1024"                                     
      prio: "1"     
      netdev: "true"      
      queues: "0, 3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39"  
    - rxring_id: "1"                                         
      desc_count: "1024"                                     
      prio: "1"    
      netdev: "true"      
      queues: "1, 4, 7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40"  
    - rxring_id: "2"                                         
      desc_count: "1024"                                     
      prio: "1"
      netdev: "true"      
      queues: "2, 5, 8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 47" 
    - rxring_id: "3"                                         
      desc_count: "1024"                                     
      prio: "1"     
      queues: "42, 43, 44, 45, 46" 
    sys_clk: "1720"
    ifc_clk: "1200"
    mac_clk: "1340"

  devports:
  - id: "0"
    sysport: "1000"
    type: "cpu"
  - fec: "KRFEC"
    id: "89"
    lanes: "0:1"
    serdes_group: "11"
    speed: "25G"
    sysport: "89"
    type: "eth"
  - fec: "KRFEC"
    id: "90"
    lanes: "1:1"
    serdes_group: "11"
    speed: "25G"
    sysport: "90"
    type: "eth"
  - fec: "KRFEC"
    id: "91"
    lanes: "2:1"
    serdes_group: "11"
    speed: "25G"
    sysport: "91"
    type: "eth"
  - fec: "KRFEC"
    id: "92"
    lanes: "3:1"
    serdes_group: "11"
    speed: "25G"
    sysport: "92"
    type: "eth"
  - fec: "KRFEC"
    id: "81"
    lanes: "0:1"
    serdes_group: "10"
    speed: "25G"
    sysport: "81"
    type: "eth"
  - fec: "KRFEC"
    id: "82"
    lanes: "1:1"
    serdes_group: "10"
    speed: "25G"
    sysport: "82"
    type: "eth"
  - fec: "KRFEC"
    id: "83"
    lanes: "2:1"
    serdes_group: "10"
    speed: "25G"
    sysport: "83"
    type: "eth"
  - fec: "KRFEC"
    id: "84"
    lanes: "3:1"
    serdes_group: "10"
    speed: "25G"
    sysport: "84"
    type: "eth"
  - fec: "KRFEC"
    id: "73"
    lanes: "0:1"
    serdes_group: "9"
    speed: "25G"
    sysport: "73"
    type: "eth"
  - fec: "KRFEC"
    id: "74"
    lanes: "1:1"
    serdes_group: "9"
    speed: "25G"
    sysport: "74"
    type: "eth"
  - fec: "KRFEC"
    id: "75"
    lanes: "2:1"
    serdes_group: "9"
    speed: "25G"
    sysport: "75"
    type: "eth"
  - fec: "KRFEC"
    id: "76"
    lanes: "3:1"
    serdes_group: "9"
    speed: "25G"
    sysport: "76"
    type: "eth"
  - fec: "KRFEC"
    id: "65"
    lanes: "0:1"
    serdes_group: "8"
    speed: "25G"
    sysport: "65"
    type: "eth"
  - fec: "KRFEC"
    id: "66"
    lanes: "1:1"
    serdes_group: "8"
    speed: "25G"
    sysport: "66"
    type: "eth"
  - fec: "KRFEC"
    id: "67"
    lanes: "2:1"
    serdes_group: "8"
    speed: "25G"
    sysport: "67"
    type: "eth"
  - fec: "KRFEC"
    id: "68"
    lanes: "3:1"
    serdes_group: "8"
    speed: "25G"
    sysport: "68"
    type: "eth"
  - fec: "KRFEC"
    id: "57"
    lanes: "0:1"
    serdes_group: "7"
    speed: "25G"
    sysport: "57"
    type: "eth"
  - fec: "KRFEC"
    id: "58"
    lanes: "1:1"
    serdes_group: "7"
    speed: "25G"
    sysport: "58"
    type: "eth"
  - fec: "KRFEC"
    id: "59"
    lanes: "2:1"
    serdes_group: "7"
    speed: "25G"
    sysport: "59"
    type: "eth"
  - fec: "KRFEC"
    id: "60"
    lanes: "3:1"
    serdes_group: "7"
    speed: "25G"
    sysport: "60"
    type: "eth"
  - fec: "KRFEC"
    id: "49"
    lanes: "0:1"
    serdes_group: "6"
    speed: "25G"
    sysport: "49"
    type: "eth"
  - fec: "KRFEC"
    id: "50"
    lanes: "1:1"
    serdes_group: "6"
    speed: "25G"
    sysport: "50"
    type: "eth"
  - fec: "KRFEC"
    id: "51"
    lanes: "2:1"
    serdes_group: "6"
    speed: "25G"
    sysport: "51"
    type: "eth"
  - fec: "KRFEC"
    id: "52"
    lanes: "3:1"
    serdes_group: "6"
    speed: "25G"
    sysport: "52"
    type: "eth"
  - fec: "KRFEC"
    id: "41"
    lanes: "0:1"
    serdes_group: "5"
    speed: "25G"
    sysport: "41"
    type: "eth"
  - fec: "KRFEC"
    id: "42"
    lanes: "1:1"
    serdes_group: "5"
    speed: "25G"
    sysport: "42"
    type: "eth"
  - fec: "KRFEC"
    id: "43"
    lanes: "2:1"
    serdes_group: "5"
    speed: "25G"
    sysport: "43"
    type: "eth"
  - fec: "KRFEC"
    id: "44"
    lanes: "3:1"
    serdes_group: "5"
    speed: "25G"
    sysport: "44"
    type: "eth"
  - fec: "KRFEC"
    id: "33"
    lanes: "0:1"
    serdes_group: "4"
    speed: "25G"
    sysport: "33"
    type: "eth"
  - fec: "KRFEC"
    id: "34"
    lanes: "1:1"
    serdes_group: "4"
    speed: "25G"
    sysport: "34"
    type: "eth"
  - fec: "KRFEC"
    id: "35"
    lanes: "2:1"
    serdes_group: "4"
    speed: "25G"
    sysport: "35"
    type: "eth"
  - fec: "KRFEC"
    id: "36"
    lanes: "3:1"
    serdes_group: "4"
    speed: "25G"
    sysport: "36"
    type: "eth"
  - fec: "KRFEC"
    id: "153"
    lanes: "0:1"
    serdes_group: "19"
    speed: "25G"
    sysport: "153"
    type: "eth"
  - fec: "KRFEC"
    id: "154"
    lanes: "1:1"
    serdes_group: "19"
    speed: "25G"
    sysport: "154"
    type: "eth"
  - fec: "KRFEC"
    id: "155"
    lanes: "2:1"
    serdes_group: "19"
    speed: "25G"
    sysport: "155"
    type: "eth"
  - fec: "KRFEC"
    id: "156"
    lanes: "3:1"
    serdes_group: "19"
    speed: "25G"
    sysport: "156"
    type: "eth"
  - fec: "KRFEC"
    id: "145"
    lanes: "0:1"
    serdes_group: "18"
    speed: "25G"
    sysport: "145"
    type: "eth"
  - fec: "KRFEC"
    id: "146"
    lanes: "1:1"
    serdes_group: "18"
    speed: "25G"
    sysport: "146"
    type: "eth"
  - fec: "KRFEC"
    id: "147"
    lanes: "2:1"
    serdes_group: "18"
    speed: "25G"
    sysport: "147"
    type: "eth"
  - fec: "KRFEC"
    id: "148"
    lanes: "3:1"
    serdes_group: "18"
    speed: "25G"
    sysport: "148"
    type: "eth"
  - fec: "KRFEC"
    id: "137"
    lanes: "0:1"
    serdes_group: "17"
    speed: "25G"
    sysport: "137"
    type: "eth"
  - fec: "KRFEC"
    id: "138"
    lanes: "1:1"
    serdes_group: "17"
    speed: "25G"
    sysport: "138"
    type: "eth"
  - fec: "KRFEC"
    id: "139"
    lanes: "2:1"
    serdes_group: "17"
    speed: "25G"
    sysport: "139"
    type: "eth"
  - fec: "KRFEC"
    id: "140"
    lanes: "3:1"
    serdes_group: "17"
    speed: "25G"
    sysport: "140"
    type: "eth"
  - fec: "KRFEC"
    id: "129"
    lanes: "0:1"
    serdes_group: "16"
    speed: "25G"
    sysport: "129"
    type: "eth"
  - fec: "KRFEC"
    id: "130"
    lanes: "1:1"
    serdes_group: "16"
    speed: "25G"
    sysport: "130"
    type: "eth"
  - fec: "KRFEC"
    id: "131"
    lanes: "2:1"
    serdes_group: "16"
    speed: "25G"
    sysport: "131"
    type: "eth"
  - fec: "KRFEC"
    id: "132"
    lanes: "3:1"
    serdes_group: "16"
    speed: "25G"
    sysport: "132"
    type: "eth"
  - fec: "KRFEC"
    id: "121"
    lanes: "0:1"
    serdes_group: "15"
    speed: "25G"
    sysport: "121"
    type: "eth"
  - fec: "KRFEC"
    id: "122"
    lanes: "1:1"
    serdes_group: "15"
    speed: "25G"
    sysport: "122"
    type: "eth"
  - fec: "KRFEC"
    id: "123"
    lanes: "2:1"
    serdes_group: "15"
    speed: "25G"
    sysport: "123"
    type: "eth"
  - fec: "KRFEC"
    id: "124"
    lanes: "3:1"
    serdes_group: "15"
    speed: "25G"
    sysport: "124"
    type: "eth"
  - fec: "KRFEC"
    id: "113"
    lanes: "0:1"
    serdes_group: "14"
    speed: "25G"
    sysport: "113"
    type: "eth"
  - fec: "KRFEC"
    id: "114"
    lanes: "1:1"
    serdes_group: "14"
    speed: "25G"
    sysport: "114"
    type: "eth"
  - fec: "KRFEC"
    id: "115"
    lanes: "2:1"
    serdes_group: "14"
    speed: "25G"
    sysport: "115"
    type: "eth"
  - fec: "KRFEC"
    id: "116"
    lanes: "3:1"
    serdes_group: "14"
    speed: "25G"
    sysport: "116"
    type: "eth"
  - fec: "KRFEC"
    id: "105"
    lanes: "0:1"
    serdes_group: "13"
    speed: "25G"
    sysport: "105"
    type: "eth"
  - fec: "KRFEC"
    id: "106"
    lanes: "1:1"
    serdes_group: "13"
    speed: "25G"
    sysport: "106"
    type: "eth"
  - fec: "KRFEC"
    id: "107"
    lanes: "2:1"
    serdes_group: "13"
    speed: "25G"
    sysport: "107"
    type: "eth"
  - fec: "KRFEC"
    id: "108"
    lanes: "3:1"
    serdes_group: "13"
    speed: "25G"
    sysport: "108"
    type: "eth"
  - fec: "KRFEC"
    id: "97"
    lanes: "0:1"
    serdes_group: "12"
    speed: "25G"
    sysport: "97"
    type: "eth"
  - fec: "KRFEC"
    id: "98"
    lanes: "1:1"
    serdes_group: "12"
    speed: "25G"
    sysport: "98"
    type: "eth"
  - fec: "KRFEC"
    id: "99"
    lanes: "2:1"
    serdes_group: "12"
    speed: "25G"
    sysport: "99"
    type: "eth"
  - fec: "KRFEC"
    id: "100"
    lanes: "3:1"
    serdes_group: "12"
    speed: "25G"
    sysport: "100"
    type: "eth"
  - fec: "KRFEC"
    id: "209"
    lanes: "0:1"
    serdes_group: "26"
    speed: "25G"
    sysport: "209"
    type: "eth"
  - fec: "KRFEC"
    id: "210"
    lanes: "1:1"
    serdes_group: "26"
    speed: "25G"
    sysport: "210"
    type: "eth"
  - fec: "KRFEC"
    id: "211"
    lanes: "2:1"
    serdes_group: "26"
    speed: "25G"
    sysport: "211"
    type: "eth"
  - fec: "KRFEC"
    id: "212"
    lanes: "3:1"
    serdes_group: "26"
    speed: "25G"
    sysport: "212"
    type: "eth"
  - fec: "KRFEC"
    id: "217"
    lanes: "0:1"
    serdes_group: "27"
    speed: "25G"
    sysport: "217"
    type: "eth"
  - fec: "KRFEC"
    id: "218"
    lanes: "1:1"
    serdes_group: "27"
    speed: "25G"
    sysport: "218"
    type: "eth"
  - fec: "KRFEC"
    id: "219"
    lanes: "2:1"
    serdes_group: "27"
    speed: "25G"
    sysport: "219"
    type: "eth"
  - fec: "KRFEC"
    id: "220"
    lanes: "3:1"
    serdes_group: "27"
    speed: "25G"
    sysport: "220"
    type: "eth"
  - fec: "NONE"
    id: "193"
    lanes: "0:1"
    serdes_group: "24"
    speed: "10G"
    sysport: "193"
    type: "eth"
  - fec: "NONE"
    id: "194"
    lanes: "1:1"
    serdes_group: "24"
    speed: "10G"
    sysport: "194"
    type: "eth"
  - fec: "NONE"
    id: "195"
    lanes: "2:1"
    serdes_group: "24"
    speed: "10G"
    sysport: "195"
    type: "eth"
  - fec: "NONE"
    id: "196"
    lanes: "3:1"
    serdes_group: "24"
    speed: "10G"
    sysport: "196"
    type: "eth"
  - fec: "NONE"
    id: "201"
    lanes: "0:1"
    serdes_group: "25"
    speed: "10G"
    sysport: "201"
    type: "eth"
  - fec: "NONE"
    id: "202"
    lanes: "1:1"
    serdes_group: "25"
    speed: "10G"
    sysport: "202"
    type: "eth"
  - fec: "NONE"
    id: "203"
    lanes: "2:1"
    serdes_group: "25"
    speed: "10G"
    sysport: "203"
    type: "eth"
  - fec: "NONE"
    id: "204"
    lanes: "3:1"
    serdes_group: "25"
    speed: "10G"
    sysport: "204"
    type: "eth"
  - fec: "NONE"
    id: "177"
    lanes: "0:1"
    serdes_group: "22"
    speed: "10G"
    sysport: "177"
    type: "eth"
  - fec: "NONE"
    id: "178"
    lanes: "1:1"
    serdes_group: "22"
    speed: "10G"
    sysport: "178"
    type: "eth"
  - fec: "NONE"
    id: "179"
    lanes: "2:1"
    serdes_group: "22"
    speed: "10G"
    sysport: "179"
    type: "eth"
  - fec: "NONE"
    id: "180"
    lanes: "3:1"
    serdes_group: "22"
    speed: "10G"
    sysport: "180"
    type: "eth"
  - fec: "NONE"
    id: "185"
    lanes: "0:1"
    serdes_group: "23"
    speed: "10G"
    sysport: "185"
    type: "eth"
  - fec: "NONE"
    id: "186"
    lanes: "1:1"
    serdes_group: "23"
    speed: "10G"
    sysport: "186"
    type: "eth"
  - fec: "NONE"
    id: "187"
    lanes: "2:1"
    serdes_group: "23"
    speed: "10G"
    sysport: "187"
    type: "eth"
  - fec: "NONE"
    id: "188"
    lanes: "3:1"
    serdes_group: "23"
    speed: "10G"
    sysport: "188"
    type: "eth"
  - fec: "NONE"
    id: "161"
    lanes: "0:1"
    serdes_group: "20"
    speed: "10G"
    sysport: "161"
    type: "eth"
  - fec: "NONE"
    id: "162"
    lanes: "1:1"
    serdes_group: "20"
    speed: "10G"
    sysport: "162"
    type: "eth"
  - fec: "NONE"
    id: "163"
    lanes: "2:1"
    serdes_group: "20"
    speed: "10G"
    sysport: "163"
    type: "eth"
  - fec: "NONE"
    id: "164"
    lanes: "3:1"
    serdes_group: "20"
    speed: "10G"
    sysport: "164"
    type: "eth"
  - fec: "NONE"
    id: "169"
    lanes: "0:1"
    serdes_group: "21"
    speed: "10G"
    sysport: "169"
    type: "eth"
  - fec: "NONE"
    id: "170"
    lanes: "1:1"
    serdes_group: "21"
    speed: "10G"
    sysport: "170"
    type: "eth"
  - fec: "NONE"
    id: "171"
    lanes: "2:1"
    serdes_group: "21"
    speed: "10G"
    sysport: "171"
    type: "eth"
  - fec: "NONE"
    id: "172"
    lanes: "3:1"
    serdes_group: "21"
    speed: "10G"
    sysport: "172"
    type: "eth"
  - fec: "NONE"
    id: "17"
    lanes: "0:1"
    serdes_group: "2"
    speed: "10G"
    sysport: "17"
    type: "eth"
  - fec: "NONE"
    id: "18"
    lanes: "1:1"
    serdes_group: "2"
    speed: "10G"
    sysport: "18"
    type: "eth"
  - fec: "NONE"
    id: "19"
    lanes: "2:1"
    serdes_group: "2"
    speed: "10G"
    sysport: "19"
    type: "eth"
  - fec: "NONE"
    id: "20"
    lanes: "3:1"
    serdes_group: "2"
    speed: "10G"
    sysport: "20"
    type: "eth"
  - fec: "NONE"
    id: "25"
    lanes: "0:1"
    serdes_group: "3"
    speed: "10G"
    sysport: "25"
    type: "eth"
  - fec: "NONE"
    id: "26"
    lanes: "1:1"
    serdes_group: "3"
    speed: "10G"
    sysport: "26"
    type: "eth"
  - fec: "NONE"
    id: "27"
    lanes: "2:1"
    serdes_group: "3"
    speed: "10G"
    sysport: "27"
    type: "eth"
  - fec: "NONE"
    id: "28"
    lanes: "3:1"
    serdes_group: "3"
    speed: "10G"
    sysport: "28"
    type: "eth"
  - fec: "KRFEC"
    id: "1"
    lanes: "0:4"
    serdes_group: "0"
    speed: "100G"
    sysport: "1"
    type: "eth"
  - fec: "KRFEC"
    id: "9"
    lanes: "0:4"
    serdes_group: "1"
    speed: "100G"
    sysport: "9"
    type: "eth"
  - fec: "NONE"
    id: "241"
    lanes: "0:4"
    serdes_group: "30"
    speed: "100G"
    sysport: "241"
    type: "eth"
  - fec: "NONE"
    id: "249"
    lanes: "0:4"
    serdes_group: "31"
    speed: "100G"
    sysport: "249"
    type: "eth"
  - fec: "NONE"
    id: "225"
    lanes: "0:4"
    serdes_group: "28"
    speed: "100G"
    sysport: "225"
    type: "eth"
  - fec: "NONE"
    id: "233"
    lanes: "0:4"
    serdes_group: "29"
    speed: "100G"
    sysport: "233"
    type: "eth"
  isg:
  - id: "0"
    tx_polarity: "00000000"
    rx_polarity: "10000010"
    lane_swap: "57234601"
  - id: "1"
    tx_polarity: "01000101"
    rx_polarity: "01110011"
    lane_swap: "51364072"
  - id: "2"
    tx_polarity: "00000000"
    rx_polarity: "00000010"
    lane_swap: "57043621"
  - id: "3"
    tx_polarity: "00000110"
    rx_polarity: "00100111"
    lane_swap: "56024371"
  - id: "4"
    tx_polarity: "00110101"
    rx_polarity: "00010000"
    lane_swap: "65137402"
  - id: "5"
    tx_polarity: "00000000"
    rx_polarity: "00100000"
    lane_swap: "61704253"
  - id: "6"
    tx_polarity: "10010010"
    rx_polarity: "00000100"
    lane_swap: "64027315"
  - id: "7"
    tx_polarity: "00000000"
    rx_polarity: "10111011"
    lane_swap: "60714253"
  - id: "8"
    tx_polarity: "10100110"
    rx_polarity: "00010101"
    lane_swap: "67042315"
  - id: "9"
    tx_polarity: "00000000"
    rx_polarity: "11010000"
    lane_swap: "20716453"
  - id: "10"
    tx_polarity: "00010000"
    rx_polarity: "00000000"
    lane_swap: "57026314"
  - id: "11"
    tx_polarity: "00000000"
    rx_polarity: "00010000"
    lane_swap: "37014625"
  - id: "12"
    tx_polarity: "00100001"
    rx_polarity: "00110111"
    lane_swap: "50473216"
  - id: "13"
    tx_polarity: "00001000"
    rx_polarity: "11010001"
    lane_swap: "16345702"
  - id: "14"
    tx_polarity: "11010110"
    rx_polarity: "01100100"
    lane_swap: "64107352"
  - id: "15"
    tx_polarity: "00100000"
    rx_polarity: "01001011"
    lane_swap: "46325710"
  - id: "16"
    tx_polarity: "10011001"
    rx_polarity: "00110001"
    lane_swap: "54216730"
  - id: "17"
    tx_polarity: "00001001"
    rx_polarity: "11000000"
    lane_swap: "25176304"
  - id: "18"
    tx_polarity: "00001000"
    rx_polarity: "01101010"
    lane_swap: "73405612"
  - id: "19"
    tx_polarity: "00110100"
    rx_polarity: "10001010"
    lane_swap: "25176304"
  - id: "20"
    tx_polarity: "00000000"
    rx_polarity: "00100000"
    lane_swap: "45617230"
  - id: "21"
    tx_polarity: "11100001"
    rx_polarity: "00010011"
    lane_swap: "46720531"
  - id: "22"
    tx_polarity: "00000000"
    rx_polarity: "11110111"
    lane_swap: "47236501"
  - id: "23"
    tx_polarity: "10100001"
    rx_polarity: "00000000"
    lane_swap: "76245301"
  - id: "24"
    tx_polarity: "01000000"
    rx_polarity: "00111100"
    lane_swap: "47316520"
  - id: "25"
    tx_polarity: "10111110"
    rx_polarity: "00000001"
    lane_swap: "61072543"
  - id: "26"
    tx_polarity: "00100000"
    rx_polarity: "01111000"
    lane_swap: "51627430"
  - id: "27"
    tx_polarity: "10101001"
    rx_polarity: "00000000"
    lane_swap: "24017536"
  - id: "28"
    tx_polarity: "00000000"
    rx_polarity: "10000010"
    lane_swap: "26073514"
  - id: "29"
    tx_polarity: "01001000"
    rx_polarity: "00000000"
    lane_swap: "43027615"
  - id: "30"
    tx_polarity: "00000000"
    rx_polarity: "11010010"
    lane_swap: "47235601"
  - id: "31"
    tx_polarity: "11111100"
    rx_polarity: "00000010"
    lane_swap: "46025713"
  - id: "32"
    tx_polarity: "00000000"
    rx_polarity: "00000000"
    lane_swap: "01234567"
