#r1.0.0
#
# BCM56880 32x400g port configuration.
#
# configuration yaml file
#   device:
#       <unit>:
#           <table>:
#               ?
#                   <key_fld_1>: <value>
#                   <key_fld_2>: <value>
#                   ...
#                   <key_fld_n>: <value>
#               :
#                   <data_fld_1>: <value>
#                   <data_fld_2>: <value>
#                   ...
#                   <data_fld_n>: <value>
#

---
device:
    0:
        DEVICE_CONFIG:
            # CORE CLOCK FREQUENCY
            CORE_CLK_FREQ: CLK_1350MHZ
            # PP CLOCK FREQUENCY
            PP_CLK_FREQ: CLK_1350MHZ
            VARIANT: DNA_4_9_5_0
...
---
device:
    0:
        FP_CONFIG:
            FP_ING_OPERMODE: GLOBAL_PIPE_AWARE
...
---
device:
    0:
        TM_SCHEDULER_CONFIG:
            NUM_MC_Q: NUM_MC_Q_4
...
---
bcm_device:
    0:
        global:
            sai_remap_prio_on_tnl_egress: 1
            global_flexctr_ing_action_num_reserved: 32
            global_flexctr_ing_group_num_reserved: 2
            global_flexctr_ing_pool_num_reserved: 12
            global_flexctr_ing_quant_num_reserved: 2
            global_flexctr_ing_op_profile_num_reserved: 32
            l3_intf_vlan_split_egress: 1
            pktio_mode: 1
            bcm_tunnel_term_compatible_mode: 1
            vlan_flooding_l2mc_num_reserved: 0
            l3_alpm_template: 1
            l3_alpm2_bnk_threshold: 100
            l2_hitbit_enable: 0
            uft_mode: 1
            l3_enable: 1
            ipv6_lpm_128b_enable: 1
            shared_block_mask_section: uc_bc
            skip_protocol_default_entries: 1
            sai_tunnel_support: 0
            flexctr_action_reserved_ipmc_hitbit: 1
            sai_nbr_bcast_ifp_optimized: 1
            use_all_splithorizon_groups: 1
            riot_enable: 1
            riot_overlay_l3_intf_mem_size: 8192
            riot_overlay_l3_egress_mem_size: 32768
            l3_ecmp_levels: 2
            riot_overlay_ecmp_resilient_hash_size: 16384
            sai_feat_tail_timestamp: 1
            sai_port_queue_ecn_counter: 1
            sai_field_group_auto_prioritize: 1
...
---
device:
    0:
        PC_PORT_PHYS_MAP:
            ?
                # CPU port
                PORT_ID: 0
            :
                PC_PHYS_PORT_ID: 0
            ?
                PORT_ID: 1
            :
                PC_PHYS_PORT_ID: 1
            ?
                PORT_ID: 2
            :
                PC_PHYS_PORT_ID: 9
            ?
                PORT_ID: 3
            :
                PC_PHYS_PORT_ID: 17
            ?
                PORT_ID: 4
            :
                PC_PHYS_PORT_ID: 25
            ?
                PORT_ID: 20
            :
                PC_PHYS_PORT_ID: 33
            ?
                PORT_ID: 21
            :
                PC_PHYS_PORT_ID: 41
            ?
                PORT_ID: 22
            :
                PC_PHYS_PORT_ID: 49
            ?
                PORT_ID: 23
            :
                PC_PHYS_PORT_ID: 57
            ?
                PORT_ID: 40
            :
                PC_PHYS_PORT_ID: 65
            ?
                PORT_ID: 41
            :
                PC_PHYS_PORT_ID: 73
            ?
                PORT_ID: 42
            :
                PC_PHYS_PORT_ID: 81
            ?
                PORT_ID: 43
            :
                PC_PHYS_PORT_ID: 89
            ?
                PORT_ID: 60
            :
                PC_PHYS_PORT_ID: 97
            ?
                PORT_ID: 61
            :
                PC_PHYS_PORT_ID: 105
            ?
                PORT_ID: 62
            :
                PC_PHYS_PORT_ID: 113
            ?
                PORT_ID: 63
            :
                PC_PHYS_PORT_ID: 121
            ?
                PORT_ID: 80
            :
                PC_PHYS_PORT_ID: 129
            ?
                PORT_ID: 81
            :
                PC_PHYS_PORT_ID: 137
            ?
                PORT_ID: 82
            :
                PC_PHYS_PORT_ID: 145
            ?
                PORT_ID: 83
            :
                PC_PHYS_PORT_ID: 153
            ?
                PORT_ID: 100
            :
                PC_PHYS_PORT_ID: 161
            ?
                PORT_ID: 101
            :
                PC_PHYS_PORT_ID: 169
            ?
                PORT_ID: 102
            :
                PC_PHYS_PORT_ID: 177
            ?
                PORT_ID: 103
            :
                PC_PHYS_PORT_ID: 185
            ?
                PORT_ID: 120
            :
                PC_PHYS_PORT_ID: 193
            ?
                PORT_ID: 121
            :
                PC_PHYS_PORT_ID: 201
            ?
                PORT_ID: 122
            :
                PC_PHYS_PORT_ID: 209
            ?
                PORT_ID: 123
            :
                PC_PHYS_PORT_ID: 217
            ?
                PORT_ID: 140
            :
                PC_PHYS_PORT_ID: 225
            ?
                PORT_ID: 141
            :
                PC_PHYS_PORT_ID: 233
            ?
                PORT_ID: 142
            :
                PC_PHYS_PORT_ID: 241
            ?
                PORT_ID: 143
            :
                PC_PHYS_PORT_ID: 249
            ?
                # management port
                PORT_ID: 38
            :
                PC_PHYS_PORT_ID: 257
            ?
                # management port
                PORT_ID: 118
            :
                PC_PHYS_PORT_ID: 259
...
---
device:
    0:
        PC_PORT:
            ?
                PORT_ID: 0
            :
                &port_mode_10g
                ENABLE: 0
                SPEED: 10000
                NUM_LANES: 1
            ?
                PORT_ID: [[1, 4],
                          [20, 23],
                          [40, 43],
                          [60, 63],
                          [80, 83],
                          [100, 103],
                          [120, 123],
                          [140, 143]]
            :
                &port_mode_400g
                ENABLE: 0
                SPEED: 400000
                NUM_LANES: 8
                FEC_MODE: PC_FEC_RS544_2XN
                LINK_TRAINING: 1
                MAX_FRAME_SIZE: 9416
            ?
                PORT_ID: [38,     # Management port 0 (Pipe 1)
                          118]    # Management port 1 (Pipe 3)
            :
                &port_mode_10g_xfi
                ENABLE: 0
                SPEED: 10000
                NUM_LANES: 1
                MAX_FRAME_SIZE: 9416
...
---
device:
    0:
        # Per pipe flex counter configuration
        CTR_EFLEX_CONFIG:
            CTR_ING_EFLEX_OPERMODE_PIPEUNIQUE: 0
            CTR_EGR_EFLEX_OPERMODE_PIPEUNIQUE: 0
...
#
# $Copyright: (c) 2019 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#
# BCM56880 PC_PM_CORE configuration for K board.
#
# $Copyright:.$
#

---
device:
    0:
        PC_PM_CORE:
            ?
                PC_PM_ID: 1
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x27413065
                TX_LANE_MAP: 0x46270513
                RX_POLARITY_FLIP: 0x0a
                TX_POLARITY_FLIP: 0x4d
            ?
                PC_PM_ID: 2
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x02741365
                TX_LANE_MAP: 0x51306274
                RX_POLARITY_FLIP: 0xfd
                TX_POLARITY_FLIP: 0x2c
            ?
                PC_PM_ID: 3
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x65731402
                TX_LANE_MAP: 0x04731265
                RX_POLARITY_FLIP: 0xf5
                TX_POLARITY_FLIP: 0xba
            ?
                PC_PM_ID: 4
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x01563427
                TX_LANE_MAP: 0x45231706
                RX_POLARITY_FLIP: 0x35
                TX_POLARITY_FLIP: 0xe4
            ?
                PC_PM_ID: 5
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x63047521
                TX_LANE_MAP: 0x41706253
                RX_POLARITY_FLIP: 0xf5
                TX_POLARITY_FLIP: 0xf2
            ?
                PC_PM_ID: 6
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x20643175
                TX_LANE_MAP: 0x65237410
                RX_POLARITY_FLIP: 0xff
                TX_POLARITY_FLIP: 0x7f
            ?
                PC_PM_ID: 7
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x64307521
                TX_LANE_MAP: 0x12650437
                RX_POLARITY_FLIP: 0xf5
                TX_POLARITY_FLIP: 0xde
            ?
                PC_PM_ID: 8
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x23417065
                TX_LANE_MAP: 0x46231705
                RX_POLARITY_FLIP: 0xff
                TX_POLARITY_FLIP: 0xb5
            ?
                PC_PM_ID: 9
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x32406175
                TX_LANE_MAP: 0x16370425
                RX_POLARITY_FLIP: 0x0a
                TX_POLARITY_FLIP: 0x45
            ?
                PC_PM_ID: 10
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x74306521
                TX_LANE_MAP: 0x01352674
                RX_POLARITY_FLIP: 0x00
                TX_POLARITY_FLIP: 0x06
            ?
                PC_PM_ID: 11
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x21743065
                TX_LANE_MAP: 0x41537062
                RX_POLARITY_FLIP: 0x0a
                TX_POLARITY_FLIP: 0x37
            ?
                PC_PM_ID: 12
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x67042531
                TX_LANE_MAP: 0x74530162
                RX_POLARITY_FLIP: 0x00
                TX_POLARITY_FLIP: 0x42
            ?
                PC_PM_ID: 13
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x10652437
                TX_LANE_MAP: 0x76051324
                RX_POLARITY_FLIP: 0x0a
                TX_POLARITY_FLIP: 0xc5
            ?
                PC_PM_ID: 14
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x65037412
                TX_LANE_MAP: 0x04731562
                RX_POLARITY_FLIP: 0x00
                TX_POLARITY_FLIP: 0x08
            ?
                PC_PM_ID: 15
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x02741365
                TX_LANE_MAP: 0x60425371
                RX_POLARITY_FLIP: 0x0a
                TX_POLARITY_FLIP: 0xc4
            ?
                PC_PM_ID: 16
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x32506174
                TX_LANE_MAP: 0x01235764
                RX_POLARITY_FLIP: 0xff
                TX_POLARITY_FLIP: 0xfc
            ?
                PC_PM_ID: 17
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x32416075
                TX_LANE_MAP: 0x15430627
                RX_POLARITY_FLIP: 0x0a
                TX_POLARITY_FLIP: 0x4d
            ?
                PC_PM_ID: 18
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x12740365
                TX_LANE_MAP: 0x61405372
                RX_POLARITY_FLIP: 0xff
                TX_POLARITY_FLIP: 0x41
            ?
                PC_PM_ID: 19
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x65037412
                TX_LANE_MAP: 0x01247653
                RX_POLARITY_FLIP: 0xf5
                TX_POLARITY_FLIP: 0xf6
            ?
                PC_PM_ID: 20
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x10652437
                TX_LANE_MAP: 0x41507263
                RX_POLARITY_FLIP: 0xff
                TX_POLARITY_FLIP: 0xf7
            ?
                PC_PM_ID: 21
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x23561704
                TX_LANE_MAP: 0x62437051
                RX_POLARITY_FLIP: 0xf5
                TX_POLARITY_FLIP: 0x7a
            ?
                PC_PM_ID: 22
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x20743165
                TX_LANE_MAP: 0x42537160
                RX_POLARITY_FLIP: 0xff
                TX_POLARITY_FLIP: 0xf7
            ?
                PC_PM_ID: 23
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x74206531
                TX_LANE_MAP: 0x03471562
                RX_POLARITY_FLIP: 0xf5
                TX_POLARITY_FLIP: 0xf9
            ?
                PC_PM_ID: 24
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x23406175
                TX_LANE_MAP: 0x60217453
                RX_POLARITY_FLIP: 0xff
                TX_POLARITY_FLIP: 0x75
            ?
                PC_PM_ID: 25
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x23506174
                TX_LANE_MAP: 0x75243016
                RX_POLARITY_FLIP: 0x0a
                TX_POLARITY_FLIP: 0x04
            ?
                PC_PM_ID: 26
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x64307521
                TX_LANE_MAP: 0x57134602
                RX_POLARITY_FLIP: 0x00
                TX_POLARITY_FLIP: 0x0e
            ?
                PC_PM_ID: 27
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x30742165
                TX_LANE_MAP: 0x30645172
                RX_POLARITY_FLIP: 0x0a
                TX_POLARITY_FLIP: 0x25
            ?
                PC_PM_ID: 28
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x76042531
                TX_LANE_MAP: 0x31657024
                RX_POLARITY_FLIP: 0x00
                TX_POLARITY_FLIP: 0x2a
            ?
                PC_PM_ID: 29
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x23651407
                TX_LANE_MAP: 0x26034715
                RX_POLARITY_FLIP: 0x0a
                TX_POLARITY_FLIP: 0x47
            ?
                PC_PM_ID: 30
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x17425603
                TX_LANE_MAP: 0x07431625
                RX_POLARITY_FLIP: 0xaa
                TX_POLARITY_FLIP: 0x0c
            ?
                PC_PM_ID: 31
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x12740365
                TX_LANE_MAP: 0x74503162
                RX_POLARITY_FLIP: 0x0a
                TX_POLARITY_FLIP: 0x1f
            ?
                PC_PM_ID: 32
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x32406175
                TX_LANE_MAP: 0x32147605
                RX_POLARITY_FLIP: 0xff
                TX_POLARITY_FLIP: 0x55
...


