ifcs:
  options:
    log_level: "info"
nodes:
- node_id: "0"
  options:
    sd_low_power_mode_global_default: "true"
    sku: "configs/sku/innovium.77700_A"
    netdev:
    - auto_create: "no"
      multi_interface: "yes"
    buffer_management_mode: "api_driven"
    max_lossless_tc: "2"
    ilpm_enable: "1"
    forward_profile: "IFCS_FORWARD_PROFILE_ID_PROFILE_E"
    ecn_stats_enable: "1"
    txring:
    - txring_id: "0"
      desc_count: "1024"
      prio: "1"
      netdev: "true"
    - txring_id: "1"
      desc_count: "1024"
      prio: "1"
      netdev: "true"
    - txring_id: "2"
      desc_count: "1024"
      prio: "1"
      netdev: "true"
    - txring_id: "3"
      desc_count: "1024"
      prio: "1"
      netdev: "true"
    rxring:
    - rxring_id: "0"
      desc_count: "1024"
      prio: "1"
      netdev: "true"
      queues: "0, 3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39"
    - rxring_id: "1"
      desc_count: "1024"
      prio: "1"
      netdev: "true"
      queues: "1, 4, 7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40"
    - rxring_id: "2"
      desc_count: "1024"
      prio: "1"
      netdev: "true"
      queues: "2, 5, 8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 47"
    - rxring_id: "3"
      desc_count: "1024"
      prio: "1"
      queues: "42, 43, 44, 45, 46"
    sys_clk: "1720"
    ifc_clk: "1200"
    mac_clk: "1340"

  devports:
  - id: "0"
    sysport: "1000"
    type: "cpu"
  - fec: "KPFEC"
    id: "217"
    lanes: "0:8"
    serdes_group: "27"
    speed: "400G"
    sysport: "217"
    type: "eth"
  - fec: "KPFEC"
    id: "209"
    lanes: "0:8"
    serdes_group: "26"
    speed: "400G"
    sysport: "209"
    type: "eth"
  - fec: "KPFEC"
    id: "201"
    lanes: "0:8"
    serdes_group: "25"
    speed: "400G"
    sysport: "201"
    type: "eth"
  - fec: "KPFEC"
    id: "193"
    lanes: "0:8"
    serdes_group: "24"
    speed: "400G"
    sysport: "193"
    type: "eth"
  - fec: "KPFEC"
    id: "185"
    lanes: "0:8"
    serdes_group: "23"
    speed: "400G"
    sysport: "185"
    type: "eth"
  - fec: "KPFEC"
    id: "177"
    lanes: "0:8"
    serdes_group: "22"
    speed: "400G"
    sysport: "177"
    type: "eth"
  - fec: "KPFEC"
    id: "169"
    lanes: "0:8"
    serdes_group: "21"
    speed: "400G"
    sysport: "169"
    type: "eth"
  - fec: "KPFEC"
    id: "161"
    lanes: "0:8"
    serdes_group: "20"
    speed: "400G"
    sysport: "161"
    type: "eth"
  - fec: "KPFEC"
    id: "249"
    lanes: "0:8"
    serdes_group: "31"
    speed: "400G"
    sysport: "249"
    type: "eth"
  - fec: "KPFEC"
    id: "241"
    lanes: "0:8"
    serdes_group: "30"
    speed: "400G"
    sysport: "241"
    type: "eth"
  - fec: "KPFEC"
    id: "233"
    lanes: "0:8"
    serdes_group: "29"
    speed: "400G"
    sysport: "233"
    type: "eth"
  - fec: "KPFEC"
    id: "225"
    lanes: "0:8"
    serdes_group: "28"
    speed: "400G"
    sysport: "225"
    type: "eth"
  - fec: "KPFEC"
    id: "153"
    lanes: "0:8"
    serdes_group: "19"
    speed: "400G"
    sysport: "153"
    type: "eth"
  - fec: "KPFEC"
    id: "145"
    lanes: "0:8"
    serdes_group: "18"
    speed: "400G"
    sysport: "145"
    type: "eth"
  - fec: "KPFEC"
    id: "137"
    lanes: "0:8"
    serdes_group: "17"
    speed: "400G"
    sysport: "137"
    type: "eth"
  - fec: "KPFEC"
    id: "129"
    lanes: "0:8"
    serdes_group: "16"
    speed: "400G"
    sysport: "129"
    type: "eth"
  - fec: "KPFEC"
    id: "121"
    lanes: "0:8"
    serdes_group: "15"
    speed: "400G"
    sysport: "121"
    type: "eth"
  - fec: "KPFEC"
    id: "113"
    lanes: "0:8"
    serdes_group: "14"
    speed: "400G"
    sysport: "113"
    type: "eth"
  - fec: "KPFEC"
    id: "105"
    lanes: "0:8"
    serdes_group: "13"
    speed: "400G"
    sysport: "105"
    type: "eth"
  - fec: "KPFEC"
    id: "97"
    lanes: "0:8"
    serdes_group: "12"
    speed: "400G"
    sysport: "97"
    type: "eth"
  - fec: "KPFEC"
    id: "25"
    lanes: "0:8"
    serdes_group: "3"
    speed: "400G"
    sysport: "25"
    type: "eth"
  - fec: "KPFEC"
    id: "17"
    lanes: "0:8"
    serdes_group: "2"
    speed: "400G"
    sysport: "17"
    type: "eth"
  - fec: "KPFEC"
    id: "9"
    lanes: "0:8"
    serdes_group: "1"
    speed: "400G"
    sysport: "9"
    type: "eth"
  - fec: "KPFEC"
    id: "1"
    lanes: "0:8"
    serdes_group: "0"
    speed: "400G"
    sysport: "1"
    type: "eth"
  - fec: "KPFEC"
    id: "89"
    lanes: "0:8"
    serdes_group: "11"
    speed: "400G"
    sysport: "89"
    type: "eth"
  - fec: "KPFEC"
    id: "81"
    lanes: "0:8"
    serdes_group: "10"
    speed: "400G"
    sysport: "81"
    type: "eth"
  - fec: "KPFEC"
    id: "73"
    lanes: "0:8"
    serdes_group: "9"
    speed: "400G"
    sysport: "73"
    type: "eth"
  - fec: "KPFEC"
    id: "65"
    lanes: "0:8"
    serdes_group: "8"
    speed: "400G"
    sysport: "65"
    type: "eth"
  - fec: "KPFEC"
    id: "57"
    lanes: "0:8"
    serdes_group: "7"
    speed: "400G"
    sysport: "57"
    type: "eth"
  - fec: "KPFEC"
    id: "49"
    lanes: "0:8"
    serdes_group: "6"
    speed: "400G"
    sysport: "49"
    type: "eth"
  - fec: "KPFEC"
    id: "41"
    lanes: "0:8"
    serdes_group: "5"
    speed: "400G"
    sysport: "41"
    type: "eth"
  - fec: "KPFEC"
    id: "33"
    lanes: "0:8"
    serdes_group: "4"
    speed: "400G"
    sysport: "33"
    type: "eth"
  isg:
  - id: "32"
    lane_swap: "01234567"
    rx_polarity: "00000000"
    tx_polarity: "00000000"
  - id: "0"
    lane_swap: "01234567"
    tx_polarity: "00000000"
    rx_polarity: "10000000"
  - id: "1"
    lane_swap: "71645320"
    tx_polarity: "01010111"
    rx_polarity: "10100100"
  - id: "2"
    lane_swap: "01234567"
    tx_polarity: "01000010"
    rx_polarity: "10000100"
  - id: "3"
    lane_swap: "01234567"
    tx_polarity: "11000110"
    rx_polarity: "10001011"
  - id: "4"
    lane_swap: "07264513"
    tx_polarity: "00011001"
    rx_polarity: "11111000"
  - id: "5"
    lane_swap: "34175620"
    tx_polarity: "00001000"
    rx_polarity: "10110000"
  - id: "6"
    lane_swap: "07214563"
    tx_polarity: "00010001"
    rx_polarity: "00110010"
  - id: "7"
    lane_swap: "74653120"
    tx_polarity: "00001000"
    rx_polarity: "00110001"
  - id: "8"
    lane_swap: "07264513"
    tx_polarity: "01000011"
    rx_polarity: "01110001"
  - id: "9"
    lane_swap: "75634120"
    tx_polarity: "00001100"
    rx_polarity: "00101001"
  - id: "10"
    lane_swap: "07264513"
    tx_polarity: "00010001"
    rx_polarity: "01100000"
  - id: "11"
    lane_swap: "71634520"
    tx_polarity: "01001010"
    rx_polarity: "10101001"
  - id: "12"
    lane_swap: "01236547"
    tx_polarity: "00000001"
    rx_polarity: "10000010"
  - id: "13"
    lane_swap: "21374560"
    tx_polarity: "00010011"
    rx_polarity: "10001000"
  - id: "14"
    lane_swap: "05214763"
    tx_polarity: "00000000"
    rx_polarity: "00000000"
  - id: "15"
    lane_swap: "61234570"
    tx_polarity: "11000000"
    rx_polarity: "00110010"
  - id: "16"
    lane_swap: "01234765"
    tx_polarity: "00000000"
    rx_polarity: "00000000"
  - id: "17"
    lane_swap: "61234570"
    tx_polarity: "00001010"
    rx_polarity: "10000111"
  - id: "18"
    lane_swap: "01234567"
    tx_polarity: "00000000"
    rx_polarity: "00000100"
  - id: "19"
    lane_swap: "01234567"
    tx_polarity: "10001000"
    rx_polarity: "11101011"
  - id: "20"
    lane_swap: "01234567"
    tx_polarity: "01000010"
    rx_polarity: "00100000"
  - id: "21"
    lane_swap: "05243176"
    tx_polarity: "00100110"
    rx_polarity: "00000011"
  - id: "22"
    lane_swap: "06214735"
    tx_polarity: "01000100"
    rx_polarity: "00110000"
  - id: "23"
    lane_swap: "01234567"
    tx_polarity: "01011010"
    rx_polarity: "10101010"
  - id: "24"
    lane_swap: "01234567"
    tx_polarity: "01001111"
    rx_polarity: "01100001"
  - id: "25"
    lane_swap: "03251467"
    tx_polarity: "00000000"
    rx_polarity: "10110010"
  - id: "26"
    lane_swap: "01234567"
    tx_polarity: "01000001"
    rx_polarity: "00100010"
  - id: "27"
    lane_swap: "04251367"
    tx_polarity: "01101001"
    rx_polarity: "11100001"
  - id: "28"
    lane_swap: "01234567"
    tx_polarity: "10100100"
    rx_polarity: "01010110"
  - id: "29"
    lane_swap: "01254367"
    tx_polarity: "00010011"
    rx_polarity: "10111001"
  - id: "30"
    lane_swap: "01234567"
    tx_polarity: "00000000"
    rx_polarity: "01000101"
  - id: "31"
    lane_swap: "01234567"
    tx_polarity: "00000110"
    rx_polarity: "11100011"

