# The azure pipeline template for Official build, and upgrade version build

parameters:
- name: 'jobFilters'
  type: object
  default: ''
- name: 'buildOptions'
  type: string
  default: 'SONIC_CONFIG_BUILD_JOBS=1'
- name: 'preSteps'
  type: stepList
  default: []
- name: 'postSteps'
  type: stepList
  default: []

jobs:
- template: azure-pipelines-image-template.yml
  parameters:
    jobFilters: ${{ parameters.jobFilters }}
    preSteps: ${{ parameters.preSteps }}
    postSteps: ${{ parameters.postSteps }}
    jobVariables:
      PLATFORM_AZP: $(GROUP_NAME)
      PLATFORM_ARCH: amd64
      BUILD_OPTIONS: ${{ parameters.buildOptions }}
      dbg_image: false
      swi_image: false
      raw_image: false
      sync_rpc_image: false
      platform_rpc: false
    jobGroups:
      - name: vs
        variables:
          dbg_image: true
      - name: barefoot
        variables:
          swi_image: true
      - name: broadcom
        variables:
          dbg_image: true
          swi_image: true
          raw_image: true
          sync_rpc_image: true
          platform_rpc: brcm
      - name: centec
        variables:
          dbg_image: true
          sync_rpc_image: true
          platform_rpc: centec
      - name: centec-arm64
        pool: sonicbld_8c
        variables:
          arch: arm64
          timeoutInMinutes: 1800
      - name: generic
        variables:
          dbg_image: true
      - name: innovium
        variables:
          swi_image: true
      - name: marvell-armhf
        pool: sonicbld_8c
        variables:
          arch: armhf
          timeoutInMinutes: 1800
      - name: mellanox
        variables:
          dbg_image: true
          sync_rpc_image: true
          platform_rpc: mlnx
      - name: nephos
        variables:
          dbg_image: true
          sync_rpc_image: true
          platform_rpc: nephos
    buildSteps:
      - bash: |
          if [ $(GROUP_NAME) == vs ]; then
            if [ $(dbg_image) == true ]; then
              make $BUILD_OPTIONS INSTALL_DEBUG_TOOLS=y target/sonic-vs.img.gz && mv target/sonic-vs.img.gz target/sonic-vs-dbg.img.gz
            fi
            make $BUILD_OPTIONS target/docker-sonic-vs.gz target/sonic-vs.img.gz target/docker-ptf.gz
          else
            if [ $(dbg_image) == true ]; then
              make  $BUILD_OPTIONS INSTALL_DEBUG_TOOLS=y target/sonic-$(GROUP_NAME).bin && \
                mv target/sonic-$(GROUP_NAME).bin target/sonic-$(GROUP_NAME)-dbg.bin
            fi
            if [ $(swi_image) == true ]; then
              make $BUILD_OPTIONS ENABLE_IMAGE_SIGNATURE=y target/sonic-aboot-$(GROUP_NAME).swi
            fi
            if [ $(raw_image) == true ]; then
              make $BUILD_OPTIONS target/sonic-$(GROUP_NAME).raw
            fi
            if [ $(sync_rpc_image) == true ]; then
              make $BUILD_OPTIONS ENABLE_SYNCD_RPC=y target/docker-syncd-$(platform_rpc)-rpc.gz
            fi
            make $BUILD_OPTIONS target/sonic-$(GROUP_NAME).bin
          fi
