# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

schedules:
- cron: "0 8 * * *"
  displayName: Daily midnight build
  branches:
    include:
    - master
  always: true

stages:
- stage: Build
  pool: sonicbld

  jobs:
  - template: build-template.yml
    parameters:
      platform: broadcom
      platform_short: brcm
      cache_mode: wcache
      dbg_image: true
      swi_image: true
      raw_image: true
      sync_rpc_image: true
