# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

schedules:
- cron: "0 8 * * *"
  displayName: Daily midnight build
  branches:
    include:
    - master
    - 202012
  always: true
- cron: "0 4 * * *"
  displayName: nightly build for release
  branches:
    include:
    - 201911
    - 201811

resources:
  repositories:
  - repository: buildimage
    type: github
    name: sonic-net/sonic-buildimage
    ref: master
    endpoint: sonic-net

trigger: none
pr: none

variables:
- template: .azure-pipelines/template-variables.yml@buildimage

stages:
- stage: Build
  pool: sonicbld
  variables:
  - name: CACHE_MODE
    value: wcache
  - template: .azure-pipelines/azure-pipelines-repd-build-variables.yml@buildimage
  jobs:
  - template: azure-pipelines-build.yml
    parameters:
      buildOptions: 'USERNAME=admin SONIC_BUILD_JOBS=$(nproc) ${{ variables.VERSION_CONTROL_OPTIONS }}'
      jobFilters: none
      ${{ if contains(variables['Build.DefinitionName'], 'cross') }}:
        qemuOrCrossBuild: true
