variables:
  DEFAULT_CONTAINER_REGISTRY: 'publicmirror.azurecr.io'
  COMMON_LIB_BUILD_ENVS: 'bullseye'
  SONIC_SLAVE_DOCKER_DRIVER: 'overlay2'
  SONIC_BUILD_RETRY_COUNT: 3
  SONIC_BUILD_RETRY_INTERVAL: 600
  DOCKER_BUILDKIT: 0
  DOCKER_BUILD_TIMEOUT: 3600
  MIRROR_SNAPSHOT: y
