steps:
- ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
  - script: |
      set -ex
      tar_branch=origin/$(System.PullRequest.TargetBranch)
      # Check if k8s master entrance script is changed
      k8s_master_changed=$(git diff $tar_branch..HEAD --name-only | grep -F files/image_config/kubernetes/kubernetes_master_entrance.sh)
      if [ -z "$k8s_master_changed" ]; then
        echo "##vso[task.setvariable variable=K8S_OPTIONS;]INCLUDE_KUBERNETES_MASTER=n"
      else
        echo "##vso[task.setvariable variable=K8S_OPTIONS;]INCLUDE_KUBERNETES_MASTER=y"
      fi
      git diff $tar_branch..HEAD --name-only | grep -v -f .azure-pipelines/vstest-exclude && exit 0
      git diff $tar_branch..HEAD --name-only | grep -f .azure-pipelines/vstest-include && exit 0
      set +x
      echo "Skip vstest jobs"
      echo "##vso[task.setvariable variable=SKIP_VSTEST;isOutput=true]YES"
    name: SetVar
    displayName: "Check if vstest is needed."
